### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by pssguy** [BillPetti/baseballr#1]
```devtools::install_github("BillPetti/baseballr")
Downloading GitHub repo BillPetti/baseballr@master
from URL https://api.github.com/repos/BillPetti/baseballr/zipball/master
Error: Does not appear to be an R package (no DESCRIPTION)

**Comment by BillPetti** [comment]
The package is in a very early development stage, it has not been compiled, etc. You can experiment with the individual functions, just be sure to have the dplyr, rvest, XML, and reldist packages installed and loaded.

**Comment by BillPetti** [comment]
FYI, you can now install and use the package via devtools.
