### ISSUE TITLE
Problem Installing  

### ISSUE THREAD

**Issue by owen2021** [BillPetti/baseballr#100]
<img width="1169" alt="Screen Shot 2019-06-28 at 10 30 54 AM" src="https://user-images.githubusercontent.com/52329602/60360169-f1589c00-998f-11e9-8b82-8e53bc58ed44.png">

Hey Bill,
I'm fairly new to R, especially downloading packages. I'm really interested in your baseball package and want to explore baseball data using R but I'm having problems installing. I attached a screenshot of the code I ran from following the directions on your website. I'm currently running R version 3.5.2 for MacOS Mojave Version 10.14
Would the problem stem from not having the latest version installed?

Thank you

**Comment by BillPetti** [comment]
It looks like you have to install the `janitor` package?: 

`there is no package called janitor`

I probably need to add that to the package in a more formal way.

**Comment by beanumber** [comment]
I believe that PR https://github.com/BillPetti/baseballr/pull/101 will fix this issue. The problem is that `janitor` wasn't listed in `DESCRIPTION`.

**Comment by owen2021** [comment]
i got it all working! Thank you both for the help.
