### ISSUE TITLE
Installation Error - cannot remove prior package

### ISSUE THREAD

**Issue by TimWheeler2006** [BillPetti/baseballr#102]
Hello,

I seem to be having a very similar issue as was described here, which was never answered:
https://stackoverflow.com/questions/55938608/cant-install-baseballr-package

My error message is slightly different but seems quite similar, when I try to install and run:
    install_github("BillPetti/baseballr")

It seems to run OK, but at the end it says:
    cannot remove prior installation of package ‘rlang’

**Comment by BillPetti** [comment]
The most recent version of `install_github` should ask if you want any, all, or no packages updated when installing. Does your version ask this question, and if so what are you selecting? Might be safest to None and see if that avoids the issue.

**Comment by TimWheeler2006** [comment]
That works!  I thought I tried that, but when I went back and did that, it seemed to work.
