### ISSUE TITLE
Get Game Info MLB Object 'ATT' not found

### ISSUE THREAD

**Issue by gregalytics** [BillPetti/baseballr#103]
get_game_info_mlb(567480)
Error in .f(.x[[i]], ...) : object 'Att' not found

Also, why does the field date say "Att"?

**Comment by BillPetti** [comment]
Can you provide some more information? What game is this `game_pk` associated with?

**Comment by gregalytics** [comment]
5/5/2019 Orioles vs. Yankees, Game 1 of Doubleheader. BIS game ID NYY19RS041.

**Comment by BillPetti** [comment]
I don't see an Orioles-Yankees game on that date when I run `get_game_pks_mlb("2019-05-05")`. I have noticed that some of the games and IDs from the api can get wonky, so not sure if that is the situation here.

**Comment by BillPetti** [comment]
Ah, looks like you meant `2019-05-15`. I do see that there should be some data from the api call, but need to dig into the reason for the error.

**Comment by gregalytics** [comment]
Yes, my bad there.

**Comment by BillPetti** [comment]
Looks like if attendance isn't available, the column simply isn't returned by the api call. Pushed a [fix](https://github.com/BillPetti/baseballr/commit/ef1b91b00573a9e84d9a1d95479074ed6861d6f9), let me know if you still run into trouble.
