### ISSUE TITLE
Error: Argument 2 must be length 36, not 72 in get_ncaa_baseball_roster

### ISSUE THREAD

**Issue by milesok** [BillPetti/baseballr#107]
```r
get_ncaa_baseball_roster(2, 2019)
```

Traceback:
Error: Argument 2 must be length 36, not 72
4.
stop(structure(list(message = "Argument 2 must be length 36, not 72", call = NULL, cppstack = NULL), class = c("Rcpp::exception", "C++Error", "error", "condition")))
3.
cbind_all(x)
2.
dplyr::bind_cols(roster, school_info)
1.
get_ncaa_baseball_roster(2, 2019)

replicated for same team (Abilene Christian) in other years as well as other teams

**Comment by BillPetti** [comment]
Thanks. Looks like for some teams that switched divisions the `subset` of the school info needs to include both the `teamid` and `year` conditions. I'll push a fix soon for this.

**Comment by BillPetti** [comment]
This should now work on reinstall based on [this commit](https://github.com/BillPetti/baseballr/commit/fc82642b8327e4cc90e709068d4f23394d4e2bde)
