### ISSUE TITLE
pitcher_game_log_fg not working for playerid = 18864

### ISSUE THREAD

**Issue by pwu97** [BillPetti/baseballr#108]
```r
pitcher_game_logs_fg(playerid = 18864, year = 2019)
```
gives me:

Error in `$<-.data.frame`(`*tmp*`, "K_9", value = numeric(0)) : 
  replacement has 0 rows, data has 27

A workaround im using right now is just avoiding the 18864 id. any idea why its doing this?

**Comment by pwu97** [comment]
will also add that this does not work for playerid = 19479

**Comment by BillPetti** [comment]
Looks like cases where the number of games equaled 1 was causing some issues in the parsing/formatting. Should work on reinstall.

**Comment by pwu97** [comment]
looks like it's not working for playerid = 19479.

**Comment by BillPetti** [comment]
Works for me. You may need to restart R/RStudio after a reinstall. Also may need to use `force = TRUE` in your install call to make sure the function updated.
