### ISSUE TITLE
Could not find function "variable_list"

### ISSUE THREAD

**Issue by JlyGreenGiant** [BillPetti/baseballr#115]
I'm sure this is user error, but am following your tutorial here: https://billpetti.github.io/2019-08-10-build-retrosheet-event-roster-database-rstats-baseballr/

and while trying to create column type mapping I am getting an error message at
`vars <- variable_list(for_type_mapping) %>%
  mutate(variable_name = as.character(variable_name))`
which gives me the error:

>  Error in variable_list(for_type_mapping) : 
>   could not find function "variable_list"

Probably an oversight on my end, but where does the variable_list function come from? Thanks

**Comment by BillPetti** [comment]
I need to update that tutorial, but that function can be found in my personal package at the moment ([bpettir](https://github.com/BillPetti/bpettir)). I think it should still work with that old code

**Comment by JlyGreenGiant** [comment]
I copied the function itself from your package, but that seemed to work. Thank you
