### ISSUE TITLE
Data Across Years

### ISSUE THREAD

**Issue by AlexGouv** [BillPetti/baseballr#116]
Hi  @BillPetti ,

I am trying to pull in data for multiple years and I am only getting data for the year in the _start_date_. I'm not sure if it's a bug or I'm just doing something wrong, but any help would be appreciated.

`scrape_statcast_savant(start_date = as.Date('2015-01-01'), end_date = as.Date('2018-01-01'),
                                      playerid = 545361)`

Thanks!

**Comment by BillPetti** [comment]
You cannot pull across years with this function. Also, your query can’t be more than ~7 days at a time due to their rate limiting (40k rows max). 

You can write a loop or mapping routine to collect years/across years, of course. @beanumber has a package that simplifies this for you.

**Comment by AlexGouv** [comment]
Sounds good. Thanks for the quick response!
