### ISSUE TITLE
Pulling retrosheet data

### ISSUE THREAD

**Issue by tasheff** [BillPetti/baseballr#118]
Hi Bill - I'm very new to R so I'm sure this is an issue somewhere on my end. I am trying to download the files and it looks like they aren't being fully processed by the Chadwick tools. I can see the Retrosheet files saved on my computer and it creates the all2019.csv but it's empty. Is it an issue with with the Chadwick files or is there a step I missed with installing your package? The other functions in your readme like teamconsistency are working so I'm a little lost on where I went wrong.

> require(baseballr)
> require(dplyr)
> require(readr)
> get_retrosheet_data(path_to_directory = "C:/Users/sheff/Documents/Downloads/retrosheet", years_to_acquire = 2019)
Parsed with column specification:
cols(
  `Field number` = col_double(),
  Description = col_character(),
  Header = col_character()
)
trying URL 'https://www.retrosheet.org/events/2019eve.zip'
Content type 'application/zip' length 2518906 bytes (2.4 MB)
downloaded 2.4 MB

'cwevent' is not recognized as an internal or external command,
operable program or batch file.
Parsed with column specification:
cols(
  `Field number` = col_double(),
  Description = col_character(),
  Header = col_character()
)
Error in attr(x, "names") <- as.character(value) : 
  'names' attribute [97] must be the same length as the vector [0]
In addition: Warning message:
In shell(paste(paste("cwevent -y", year, "-f 0-96"), paste(year,  :
  'cwevent -y 2019 -f 0-96 2019*.EV* > all2019.csv' execution failed with error code 1

**Comment by BillPetti** [comment]
Maybe there is an issue because you are on a Windows machine. Is this just a 2019 issue, or does the error persist when trying to grab other seasons?

**Comment by tasheff** [comment]
I get the same error for other years and while trying to pull multiple years as well.

**Comment by BillPetti** [comment]
Do you have Chadwick installed on your machine?

**Comment by BillPetti** [comment]
Still trying to think what the issue might be. In trouble shooting, I am now having an issue where I am getting about half as many rows per year as I should. Will keep trying to figure this out.

**Comment by adamott20** [comment]
@tasheff I was experiencing the same issue. It looks like the issue can be solved by placing the cwevent.exe chadwick file in the unzipped folder when using Windows. There's a comment in the function on github that mentions this. I'm not exactly sure why.

**Comment by BillPetti** [comment]
@tasheff, does @adamott20’s suggestion fix the issue?

**Comment by DailyAdamG** [comment]
Hi Bill,

I am having the same issue as tasheff, but placing the cwevent.exe file in the unzipped folder has not fixed the issue. Any help you can offer would be greatly appreciated!
