### ISSUE TITLE
"Unable to install baseballr package from GitHub"

### ISSUE THREAD

**Issue by dlock0715** [BillPetti/baseballr#119]
Trying to install the baseballr package using the following code:

devtools::install_github("BillPetti/baseballr")

I keep gettting an error saying "Error: Failed to install 'baseballr' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘digest’"

I've tried several different times and each time I get the same error with the only difference being the name of the package that can't be removed. Is there any way to fix or work around this? My apologies if this is a simple question as I am a fairly new user of R

**Comment by BillPetti** [comment]
Not sure I've seen this. Are the packages that are trying to be removed in need of updating? I wonder if that's part of the issue.

**Comment by rsmattson** [comment]
I am going to piggy back off this comment, and leave my info here. I have tried to install baseballr as well with R 3.5 and Rstudio 1.2. 

I get the following ouput:
> devtools::install_github("BillPetti/baseballr")
WARNING: Rtools is required to build R packages, but the version of Rtools previously installed in C:/Rtools has been deleted.

Please download and install Rtools custom from http://cran.r-project.org/bin/windows/Rtools/.
Downloading GitHub repo BillPetti/baseballr@master
These packages have more recent versions available.
Which would you like to update?

 1: All                                       
 2: CRAN packages only                        
 3: None                                      
 4: dplyr       (0.7.8     -> 0.8.3   ) [CRAN]
 5: ggplot2     (3.1.0     -> 3.2.1   ) [CRAN]
 6: stringr     (1.3.1     -> 1.4.0   ) [CRAN]
 7: tidyr       (0.8.2     -> 1.0.2   ) [CRAN]
 8: XML         (3.98-1.16 -> 3.99-0.3) [CRAN]
 9: xml2        (1.2.0     -> 1.2.2   ) [CRAN]
10: tibble      (2.0.1     -> 2.1.3   ) [CRAN]
11: assertthat  (0.2.0     -> 0.2.1   ) [CRAN]
12: glue        (1.3.0     -> 1.3.1   ) [CRAN]
13: pkgconfig   (2.0.2     -> 2.0.3   ) [CRAN]
14: R6          (2.3.0     -> 2.4.1   ) [CRAN]
15: Rcpp        (1.0.0     -> 1.0.3   ) [CRAN]
16: rlang       (0.4.3     -> 0.4.4   ) [CRAN]
17: tidyselect  (0.2.5     -> 1.0.0   ) [CRAN]
18: BH          (1.69.0-1  -> 1.72.0-3) [CRAN]
19: digest      (0.6.18    -> 0.6.23  ) [CRAN]
20: gtable      (0.2.0     -> 0.3.0   ) [CRAN]
21: lazyeval    (0.2.1     -> 0.2.2   ) [CRAN]
22: scales      (1.0.0     -> 1.1.0   ) [CRAN]
23: htmlwidgets (1.3       -> 1.5.1   ) [CRAN]
24: zoo         (1.8-4     -> 1.8-7   ) [CRAN]
25: broom       (0.5.1     -> 0.5.4   ) [CRAN]
26: xts         (0.11-2    -> 0.12-0  ) [CRAN]
27: quantmod    (0.4-13    -> 0.4-15  ) [CRAN]
28: htmltools   (0.3.6     -> 0.4.0   ) [CRAN]
29: plyr        (1.8.4     -> 1.8.5   ) [CRAN]
30: hexbin      (1.27.2    -> 1.28.0  ) [CRAN]
31: hms         (0.4.2     -> 0.5.3   ) [CRAN]
32: clipr       (0.5.0     -> 0.7.0   ) [CRAN]
33: httr        (1.4.0     -> 1.4.1   ) [CRAN]
34: stringi     (1.2.4     -> 1.4.5   ) [CRAN]
35: fansi       (0.4.0     -> 0.4.1   ) [CRAN]
36: pillar      (1.3.1     -> 1.4.3   ) [CRAN]
37: colorspace  (1.4-0     -> 1.4-1   ) [CRAN]
38: data.table  (1.12.0    -> 1.12.8  ) [CRAN]
39: backports   (1.1.3     -> 1.1.5   ) [CRAN]
40: TTR         (0.23-4    -> 0.23-6  ) [CRAN]
41: curl        (3.3       -> 4.3     ) [CRAN]
42: shiny       (1.2.0     -> 1.4.0   ) [CRAN]
43: httpuv      (1.4.5.1   -> 1.5.2   ) [CRAN]
44: mime        (0.6       -> 0.8     ) [CRAN]
45: xtable      (1.8-3     -> 1.8-4   ) [CRAN]
46: later       (0.7.5     -> 1.0.0   ) [CRAN]
47: promises    (1.0.1     -> 1.1.0   ) [CRAN]
48: knitr       (1.21      -> 1.27    ) [CRAN]
49: evaluate    (0.12      -> 0.14    ) [CRAN]
50: highr       (0.7       -> 0.8     ) [CRAN]
51: markdown    (0.9       -> 1.1     ) [CRAN]
52: xfun        (0.4       -> 0.12    ) [CRAN]
53: openssl     (1.2.1     -> 1.4.1   ) [CRAN]
54: sys         (2.1       -> 3.3     ) [CRAN]

Enter one or more numbers, or an empty line to skip updates:
1
dplyr       (0.7.8     -> 0.8.3   ) [CRAN]
ggplot2     (3.1.0     -> 3.2.1   ) [CRAN]
highcharter (NA        -> 0.7.0   ) [CRAN]
janitor     (NA        -> 1.2.1   ) [CRAN]
pitchRx     (NA        -> 1.8.2   ) [CRAN]
reldist     (NA        -> 1.6-6   ) [CRAN]
rvest       (NA        -> 0.3.5   ) [CRAN]
stringr     (1.3.1     -> 1.4.0   ) [CRAN]
tidyr       (0.8.2     -> 1.0.2   ) [CRAN]
XML         (3.98-1.16 -> 3.99-0.3) [CRAN]
xml2        (1.2.0     -> 1.2.2   ) [CRAN]
pbapply     (NA        -> 1.4-2   ) [CRAN]
tibble      (2.0.1     -> 2.1.3   ) [CRAN]
assertthat  (0.2.0     -> 0.2.1   ) [CRAN]
glue        (1.3.0     -> 1.3.1   ) [CRAN]
pkgconfig   (2.0.2     -> 2.0.3   ) [CRAN]
R6          (2.3.0     -> 2.4.1   ) [CRAN]
Rcpp        (1.0.0     -> 1.0.3   ) [CRAN]
rlang       (0.4.3     -> 0.4.4   ) [CRAN]
tidyselect  (0.2.5     -> 1.0.0   ) [CRAN]
BH          (1.69.0-1  -> 1.72.0-3) [CRAN]
digest      (0.6.18    -> 0.6.23  ) [CRAN]
gtable      (0.2.0     -> 0.3.0   ) [CRAN]
lazyeval    (0.2.1     -> 0.2.2   ) [CRAN]
scales      (1.0.0     -> 1.1.0   ) [CRAN]
htmlwidgets (1.3       -> 1.5.1   ) [CRAN]
rlist       (NA        -> 0.4.6.1 ) [CRAN]
zoo         (1.8-4     -> 1.8-7   ) [CRAN]
broom       (0.5.1     -> 0.5.4   ) [CRAN]
xts         (0.11-2    -> 0.12-0  ) [CRAN]
quantmod    (0.4-13    -> 0.4-15  ) [CRAN]
htmltools   (0.3.6     -> 0.4.0   ) [CRAN]
igraph      (NA        -> 1.2.4.2 ) [CRAN]
snakecase   (NA        -> 0.11.0  ) [CRAN]
XML2R       (NA        -> 0.0.6   ) [CRAN]
plyr        (1.8.4     -> 1.8.5   ) [CRAN]
hexbin      (1.27.2    -> 1.28.0  ) [CRAN]
hms         (0.4.2     -> 0.5.3   ) [CRAN]
clipr       (0.5.0     -> 0.7.0   ) [CRAN]
Hmisc       (NA        -> 4.3-0   ) [CRAN]
httr        (1.4.0     -> 1.4.1   ) [CRAN]
selectr     (NA        -> 0.4-2   ) [CRAN]
stringi     (1.2.4     -> 1.4.5   ) [CRAN]
vctrs       (NA        -> 0.2.2   ) [CRAN]
lifecycle   (NA        -> 0.1.0   ) [CRAN]
fansi       (0.4.0     -> 0.4.1   ) [CRAN]
pillar      (1.3.1     -> 1.4.3   ) [CRAN]
farver      (NA        -> 2.0.3   ) [CRAN]
colorspace  (1.4-0     -> 1.4-1   ) [CRAN]
data.table  (1.12.0    -> 1.12.8  ) [CRAN]
backports   (1.1.3     -> 1.1.5   ) [CRAN]
TTR         (0.23-4    -> 0.23-6  ) [CRAN]
curl        (3.3       -> 4.3     ) [CRAN]
shiny       (1.2.0     -> 1.4.0   ) [CRAN]
httpuv      (1.4.5.1   -> 1.5.2   ) [CRAN]
mime        (0.6       -> 0.8     ) [CRAN]
xtable      (1.8-3     -> 1.8-4   ) [CRAN]
later       (0.7.5     -> 1.0.0   ) [CRAN]
promises    (1.0.1     -> 1.1.0   ) [CRAN]
fastmap     (NA        -> 1.0.1   ) [CRAN]
RCurl       (NA        -> 1.98-1.1) [CRAN]
bitops      (NA        -> 1.0-6   ) [CRAN]
acepack     (NA        -> 1.4.1   ) [CRAN]
gridExtra   (NA        -> 2.3     ) [CRAN]
htmlTable   (NA        -> 1.13.3  ) [CRAN]
viridis     (NA        -> 0.5.1   ) [CRAN]
knitr       (1.21      -> 1.27    ) [CRAN]
checkmate   (NA        -> 1.9.4   ) [CRAN]
evaluate    (0.12      -> 0.14    ) [CRAN]
highr       (0.7       -> 0.8     ) [CRAN]
markdown    (0.9       -> 1.1     ) [CRAN]
xfun        (0.4       -> 0.12    ) [CRAN]
openssl     (1.2.1     -> 1.4.1   ) [CRAN]
sys         (2.1       -> 3.3     ) [CRAN]
Skipping 1 packages not available: latticeExtra
Installing 75 packages: dplyr, ggplot2, highcharter, janitor, pitchRx, reldist, rvest, stringr, tidyr, XML, xml2, pbapply, tibble, assertthat, glue, pkgconfig, R6, Rcpp, rlang, tidyselect, BH, digest, gtable, lazyeval, scales, htmlwidgets, rlist, zoo, broom, xts, quantmod, htmltools, igraph, snakecase, XML2R, plyr, hexbin, hms, clipr, Hmisc, httr, selectr, stringi, vctrs, lifecycle, fansi, pillar, farver, colorspace, data.table, backports, TTR, curl, shiny, httpuv, mime, xtable, later, promises, fastmap, RCurl, bitops, latticeExtra, acepack, gridExtra, htmlTable, viridis, knitr, checkmate, evaluate, highr, markdown, xfun, openssl, sys
Installing packages into ‘C:/Users/Ryan/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
Error: Failed to install 'baseballr' from GitHub:
  (converted from warning) package ‘latticeExtra’ is not available (for R version 3.5.0)

I have downloaded Rtools and placed it in my R folder, but it also is still not working. Like the OP I'm not well versed in all things R, so I'm not sure where to go from here. If I try the simple install.packages command I get this:

> install.packages("baseballr")
Installing package into ‘C:/Users/Ryan/Documents/R/win-library/3.5’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
Warning message:
package ‘baseballr’ is not available (for R version 3.5.0) 
>

**Comment by rsmattson** [comment]
I have also tried the datascrape directions from this website: https://billpetti.github.io/2018-02-19-build-statcast-database-rstats/

However the 2018 to 2019 data will not download as there is some issue with the "fielder_2" data. It seems to not want to import that. My apologies, I am waiting on my recent attempt to fully go through the program before I post the output. Thanks for posting all this on Github and being willing to respond.

**Comment by rsmattson** [comment]
As an addition, I revised the game dates in the available data file https://billpetti.github.io/2018-02-19-build-statcast-database-rstats/ to reflect the season games and breaks from 2018 and 2019.

**Comment by pappisac** [comment]
Can someone help me, please! I have been trying all day to figure this out.  I am very new to programming and R but I know how to load packages.  I installed all the needed packages.  Ran the code devtools::install_github("BillPetti/baseballr) and I continue to get this message below.  I have searched and found that others are also experiencing this but can't a fix. 
Thanks for help you can provide 

Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'vroom'
Calls: <Anonymous> ... loadNamespace -> withRestarts -> withOneRestart -> doWithOneRestart
Execution halted
ERROR: lazy loading failed for package 'baseballr'
* removing 'C:/Program Files/R/R-3.6.3/library/baseballr'
Error: Failed to install 'baseballr' from GitHub:
  (converted from warning) installation of package ‘C:/Users/npappas/AppData/Local/Temp/Rtmpov13EY/file24e078a6434b/baseballr_0.7.0.tar.gz’ had non-zero exit status

**Comment by BillPetti** [comment]
Install `vroom` first and then retry

**Comment by pappisac** [comment]
That worked! Thank you so much! Not only for this but also all your content.
