### ISSUE TITLE
calling fg_bat_leaders resulting in an error

### ISSUE THREAD

**Issue by jgoodbody** [BillPetti/baseballr#12]
"Error in leaders[1, ] : incorrect number of dimensions"

So it seems like the structure of the leaders page has changed.

**Comment by jgoodbody** [comment]
In the first line of code within the function, I changed the (23) toward the end to (24) and it appears to work correctly now. I know this has something to do with the xml nodes being scraped. I guess the list created by html_nodes is slightly different now.

**Comment by BillPetti** [comment]
Yup, the page structure changed. Just pushed a fix. Should work on reinstall. Thanks again!
