### ISSUE TITLE
Feature request: Specify team in daily_batter_bref and daily_pitcher_bref

### ISSUE THREAD

**Issue by naymikm** [BillPetti/baseballr#121]
Filtering by team does the job 99% of the time but some players have 2 teams listed (traded I assume?) so getting team specific stats for a date range becomes difficult.

**Comment by BillPetti** [comment]
Unfortunately, this isn't something that can be done. Splits by team are not provided through that search at Baseball-Reference, therefore the scraper can't format the data that way.
