### ISSUE TITLE
Cannot install Baseballr

### ISSUE THREAD

**Issue by genmiller** [BillPetti/baseballr#122]
Hi,

When I ran the code:
> library(devtools)
library(dplyr)
require(devtools)
devtools::install_github("BillPetti/Baseballr")
> 
I get the following error.
>ERROR: dependencies 'highcharter', 'janitor', 'pitchRx', 'reldist', 'XML', 'pbapply' are not available for package 'baseballr'
*removing 'C:/Program Files/R/R-3.6.2/library/baseballr'

> Error: Failed to install 'baseballr' from GitHub:
>   (converted from warning) installation of package ‘C:/Users/MYNAME/AppData/Local/Temp/RtmpErrVG7/filea68bb946a7/baseballr_0.6.0.tar.gz’ had non-zero exit status

Can you help me with what's going on here, I'm trying to understand why's this keep showing up. Using Windows running on RStudio R.ver 3.6.2

**Comment by BillPetti** [comment]
I believe it means those required packages are not installed on your machine and need to be for the packages to install.

**Comment by genmiller** [comment]
I uninstalled R and RStudio, and it worked now. Thank you for you help.
