### ISSUE TITLE
Issue With Certain Schools in ncaa_scrape

### ISSUE THREAD

**Issue by Mattf18** [BillPetti/baseballr#124]
<img width="463" alt="Screen Shot 2020-02-23 at 8 05 04 PM" src="https://user-images.githubusercontent.com/49245489/75124913-ef0e2500-5677-11ea-8ca2-a36bc62d52cc.png">

I'm getting the error in the attached screenshot with certain schools when trying to scrape data. Is there something I need to change on my end?

Thanks!

**Comment by BillPetti** [comment]
There was a bug due to a renamed column. It should work with a reinstall.
