### ISSUE TITLE
person_draft_year issue

### ISSUE THREAD

**Issue by gregalytics** [BillPetti/baseballr#125]
When you use get_draft_mlb() in 2008, it returns the incorrect year for players who were drafted again. Look at Aaron Crow that year. I estimate roughly 20% of draft seasons are wrong because of that. 

My easy fix was just mutating person_draft_year to the year that was entered:
drafts <- c(year(Sys.Date()):2008)
draft_picks <- map_df(drafts, ~get_draft_mlb(.x) %>% mutate(person_draft_year = .x))

**Comment by BillPetti** [comment]
This isn't really an issue, per se. From what I can tell, that column refers to the year the player was drafted **_and_** signed. I can add a column at the beginning, like, `year_of_draft`, to differentiate between the two.

**Comment by gregalytics** [comment]
I actually found something that is an issue. The 2017 draft does not return the player's school_name:
>get_draft_mlb(2017)

**Comment by BillPetti** [comment]
This appears to be an issue on the API's side. I see 653 NAs, so, not totally empty, but more than half. You don't see the same issue for 15, 16, 18, or 19. I'll look into it more to see if maybe they 'hid' that field somewhere different in '17, but it's likely an issue on MLB's side.
