### ISSUE TITLE
Error: Names must not be empty.

### ISSUE THREAD

**Issue by AngelClaudio** [BillPetti/baseballr#127]
When I try to run any example such as:
team_results_bref("NYM", 2015)

I get the following error:
> team_consistency(2015)
Error: Names must not be empty.
Run `rlang::last_error()` to see where the error occurred.

Not sure if this is related, but when I load the library I get this message:
Registered S3 method overwritten by 'quantmod':
  method            from
  as.zoo.data.frame zoo 

Thanks.

**Comment by BillPetti** [comment]
Something probably changed with the underlying html. I’ll have a look.

**Comment by BillPetti** [comment]
This has been fixed
