### ISSUE TITLE
Error: scrape_statcast_savant_batter() limits results to a single season

### ISSUE THREAD

**Issue by rdelrossi** [BillPetti/baseballr#130]
I've been struggling with `scrape_statcast_savant_batter()`. No matter what multi-year ranges I pass in, the return values are limited to the year of the start_date parameter. I tracked the problem down to the hfSea (season) parameter in `scrape_statcast_savant()`:

```
vars <- tibble::tribble(
     ...
    "hfSea", paste0(lubridate::year(start_date), "%7C"),
     ...   
```

Not sure if this limitation was put in by design or whether it was an oversight. Clearing it allows me to queries multiple years of data.

**Comment by BillPetti** [comment]
It was due both to the functionality not existing originally and to keep people from writing queries that would error out when it was added. I’d be willing to update it at some point. 

Also, scrape_statcast_savant is the main function that can be used to pull for specific info for players. The other functions have basically been soft deprecated.

**Comment by rdelrossi** [comment]
Understood. Thanks for the clarification.
