### ISSUE TITLE
Issues installing from GitHub using DevTools

### ISSUE THREAD

**Issue by mducondi** [BillPetti/baseballr#135]
Having issues installing the baseballr package to RStudio. Not sure what other information you might need but this is the general error message I am receiving. I have looked elsewhere, tried to change path or manually install from a folder on my Desktop but nothing is working.

I believe the error is coming from my file path having a space ("My Drive"). Not sure how else to get around this problem. Thanks!

Installing package into ‘C:/Users/My Drive/Documents/R/win-library/3.6’
(as ‘lib’ is unspecified)
* installing *source* package 'baseballr' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** inst
** byte-compile and prepare package for lazy loading
Fatal error: cannot open file 'C:\Users\My': No such file or directory

ERROR: lazy loading failed for package 'baseballr'
* removing 'C:/Users/My Drive/Documents/R/win-library/3.6/baseballr'
* restoring previous 'C:/Users/My Drive/Documents/R/win-library/3.6/baseballr'
Error: Failed to install 'baseballr' from GitHub:
  (converted from warning) installation of package ‘C:/Users/My Drive/AppData/Local/Temp/RtmpmIld9m/file222c61836d54/baseballr_0.7.0.tar.gz’ had non-zero exit status

**Comment by BillPetti** [comment]
I believe the space in the file path is the issue, but outside of renaming that directory without a space I don't know of another fix.
