### ISSUE TITLE
Missing str_extract import from stringr 

### ISSUE THREAD

**Issue by smorsink1** [BillPetti/baseballr#136]
The get_ncaa_schedule_info importFrom tag for stringr is missing str_extract.

In get_ncaa_schedule_info.R, lines 69 and 120 use str_extract. However, str_extract is not imported from stringr in the importFrom tags (only imports str_trim from stringr), so get_ncaa_schedule_info() throws an error: Error in str_extract(innings, "[[0-9]]+") : could not find function "str_extract"

**Comment by BillPetti** [comment]
This should now be fixed
