### ISSUE TITLE
scrape_statcast_savant_pitcher() returns batting data for pitchers

### ISSUE THREAD

**Issue by erictassone** [BillPetti/baseballr#14]
Hi!

Cool package, which I read about on [Exploring Baseball Data with R](https://baseballwithr.wordpress.com/2017/02/06/baseballr-package-a-first-look/)!

I am having one issue: For me, the function _scrape_statcast_savant_pitcher()_ is returning batting data for pitchers, not pitching data. I believe when building the URL the relevant part of the setting should be _player_type=pitcher_ instead of the current _player_type=batter_, based on my read of the function [here](https://github.com/BillPetti/baseballr/blob/master/R/scrape_statcast_savant_pitcher.R). When I manually make that change to the function, it returns pitching data for pitchers.

Attached is my working file in case it might help. Sorry if I overlooked something obvious.
[baseballr.txt](https://github.com/BillPetti/baseballr/files/763407/baseballr.txt)

Cheers,
Eric Tassone

**Comment by BillPetti** [comment]
Yes! Sorry, I think I was fixing a general issue with how the url changed and got caught in a copy/paste shortcut :) 

Should be good now.
