### ISSUE TITLE
Expected behavior of "scrape_savant_leaderboards" when leaderboard = "exit_velocity_barrels"

### ISSUE THREAD

**Issue by mmcgowan13** [BillPetti/baseballr#147]
It appears that the function "scrape_savant_leaderboards" ignores the min_pa parameter and thus only shows batters who are qualified, even if the abs parameter is set to something lower than qualified. This surprised me, but I thought perhaps it was expected behavior, so I'm reluctant to call it a bug. Also, I wasn't sure if perhaps it's the Baseball Savant API that's not adhering to expectations. So I wasn't sure what the expected behavior was in this circumstance.

**Comment by BillPetti** [comment]
Added to master branch via #180
