### ISSUE TITLE
Error in loadNamespace

### ISSUE THREAD

**Issue by natehutchinson** [BillPetti/baseballr#15]
Hi,

I have been trying to install baseballr using R 3.3.2 on Windows, and I get the following error:

* installing *source* package 'baseballr' ...
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called 'XML2R'
ERROR: lazy loading failed for package 'baseballr'

I have tried installing the missing package separately, but every time I do this and then try installing baseballr again I get the same error but with a different package listed as missing. Any idea how to fix this?

Thanks

**Comment by BillPetti** [comment]
Hmmm, it almost sounds like the Import packages aren't installing and loading for you. This is the list, are these the ones that keep popping up?
Imports:
    dplyr,
    lubridate,
    pitchRx,
    reldist,
    rvest,
    XML,
    xml2

**Comment by natehutchinson** [comment]
Yeah, that's the list.

**Comment by keberwein** [comment]
Try `install.packages("XML2R")` and then install `baseballr`. That should work for you.

**Comment by BillPetti** [comment]
Hmm, looks like XML2R is used in the pitchRx package and that is why it may be causing you some issues if you don't already have it installed.

**Comment by forrestdiamond** [comment]
It also requires `Hmisc`, which needs to be installed before `baseballr` will install.
