### ISSUE TITLE
Error in daily_pitcher_bref()

### ISSUE THREAD

**Issue by doanco01** [BillPetti/baseballr#156]
I am trying to pull pitcher data for the 2018-2019 seasons as two separate data frames. I am getting the same error for each (see below). This seems similar to the following [issue](https://github.com/BillPetti/baseballr/issues/93).

> pitcher_IP_2018 <- daily_pitcher_bref(t1 = "2018-03-29", t2 = "2018-10-01")
Error in names(df)[1:4] <- c("Name", "Age", "Level", "Team") : 
  'names' attribute [4] must be the same length as the vector [0]

> pitcher_IP_2019 <- daily_pitcher_bref(t1 = "2019-03-20", t2 = "2019-09-29")
Error in names(df) <- `*vtmp*` : 
  'names' attribute [4] must be the same length as the vector [0]

**Comment by BillPetti** [comment]
I don’t know if these daily functions will work again due to changes at B-Ref. See here for an alternative approach: https://billpetti.github.io/2020-05-29-build-statlines-statcast-rstats/
