### ISSUE TITLE
edge_scrape_split error

### ISSUE THREAD

**Issue by alex-susi** [BillPetti/baseballr#163]
I'm trying to use the edge_scrape_split function like so

edge_scrape_split("2015-04-06", "2015-04-07", "batter") %>%
  .[, c(1:3,7:12)] %>%
  head(10)

but keep getting this error:

Error in function (type, msg, asError = TRUE)  : 
  Could not resolve host: 

I have the devtools version of pitchRx (1.8.4) installed and all other packages are up to date, so I'm not sure what could be wrong

**Comment by BillPetti** [comment]
This looks like an issue with the `getURL` function in `pitchRx`. Not sure if there is anything I can do on my end.
