### ISSUE TITLE
get_draft_mlb not working 

### ISSUE THREAD

**Issue by gregalytics** [BillPetti/baseballr#165]
> baseballr::get_draft_mlb(2019)

Error: Can't combine `..1$pickRound` <logical> and `..2$pickRound` <character>.

**Comment by BillPetti** [comment]
Thanks. This has been fixed and should work on reinstall.

**Comment by gregalytics** [comment]
Thanks. I like that the output is simplified into 13 columns now, but not sure if team name is intentionally omitted.

**Comment by BillPetti** [comment]
Wait, there should still be 72. Can you post an example? It executed properly for me earlier.

**Comment by gregalytics** [comment]
My bad, stupid error by me - happy 4th

**Comment by BillPetti** [comment]
No worries, same to you!
