### ISSUE TITLE
NA From Fangraphs Leaderboard

### ISSUE THREAD

**Issue by jrod20033** [BillPetti/baseballr#167]
Getting NA's for LD% FB% and other percentage based stats when pulling down from Fangraphs. I had messaged about this, but it seem the issue is happening. 
![nas](https://user-images.githubusercontent.com/62019711/87700208-f7b8e200-c763-11ea-911f-89e291a867f7.PNG)

**Comment by BillPetti** [comment]
There was a bug, but should work on re-install
