### ISSUE TITLE
Bolts column not scraping on scrape_savant_leaderboard for sprint speed table

### ISSUE THREAD

**Issue by dsteinberg100** [BillPetti/baseballr#173]
On the sprint speed leaderboard on baseballsavant, there is a column called "Bolts."

https://baseballsavant.mlb.com/leaderboard/sprint_speed?year=2020&position=&team=&min=5

![image](https://user-images.githubusercontent.com/9991795/88954153-c4d81900-d24e-11ea-9bc2-225bb36f974c.png)

However, this column does not scrape in R.

![image](https://user-images.githubusercontent.com/9991795/88954209-d9b4ac80-d24e-11ea-8f46-ac737ef762b2.png)

It would be great if that column could be scraped.

**Comment by BillPetti** [comment]
As of right now, this is an issue with the Savant csv download. The function is simply reading that, not directly scraping the data from the page, and that column isn't included for some reason.
