### ISSUE TITLE
get_batting_orders error

### ISSUE THREAD

**Issue by danmalter** [BillPetti/baseballr#174]
Line 61 in the get_batting_orders function `map_df(~players(list = list, team = "home", playerid = .$playerid)) %>%` is causing an error:

Error in players(list = list, team = "home", playerid = .$playerid) : 
  object 'type' not found

**Comment by BillPetti** [comment]
Thanks. I am aware of the issue and working on a fix

**Comment by BillPetti** [comment]
This has been fixed with version 0.8.3
