### ISSUE TITLE
Error in team_results_bref function

### ISSUE THREAD

**Issue by concipaulo** [BillPetti/baseballr#179]
Seems that [baseball-reference added a new column for CLI on the schedule page](https://www.baseball-reference.com/teams/OAK/2020-schedule-scores.shtml). This causes an error when calling the `team_results_bref` function. The error can be solved adding a new argument in the `col_names` variable. 

I could create a fork and make a pull request but I think it would be more easy just change the code in the master branch.

**Comment by BillPetti** [comment]
Thanks for the heads up. This has been fixed as of #180
