### ISSUE TITLE
Issue with fg_bat_leaders() html scrape

### ISSUE THREAD

**Issue by forrestdiamond** [BillPetti/baseballr#18]
I've been trying to use the `fg_bat_leaders()` command, but it looks like the new Fangraphs layout broke the html scraper. I get an `Error in .[[24]] : subscript out of bounds`. When I tried copy and pasting the function guts to find the error I found the failure comes on the initial `read_html()` call. I assume something in the `paste0() `needs to be changed with the FG update, but I could be wrong!

Is anyone else getting this result?

**Comment by BillPetti** [comment]
Yup, page structure shifted. Try reinstalling, should work now.
