### ISSUE TITLE
Function for turning PITCHf/x or Statcast data into boxscore formatted data for use in calculating player statistics (i.e. OPS, wOBA, etc.)

### ISSUE THREAD

**Issue by BillPetti** [BillPetti/baseballr#19]

**Comment by afeierman** [comment]
Hey Bill, I'm having trouble figuring out what 'boxscore formatted' means, especially since the Statcast data doesn't include batted ball outcomes, as far as I can tell. What output are you thinking of?

**Comment by BillPetti** [comment]
Probably should have said pitch-by-pitch data, since the two are being collected and distributed generally together at this point. Basically the idea is to take the raw PITCHfx output and tag each outcome so that you can use the data to calculate custom metrics based on some grouping. So, wOBA for all pitches 95mph+ for LHH vs. LHP. Or group by batter and show their OPS on contact or on swings for a certain type of pitch, etc.

By boxscore format, I mean something along these lines:

`# Name Count X1B X2B X3B HR 
 # B. Harper 134 45 10 1 30`

I have some code that automatically tags each batted ball with a coding for single, double, triple, home run when I update my database, that might be a good jumping off point. This is based on the downloadable output you get from BaseballSavant.com:

`savant_data$hit_type <- with(savant_data, ifelse(type == "X" & grepl("Single", savant_data$events), 1,
                                                 ifelse(type == "X" & grepl("Double", savant_data$events), 2,
                                                        ifelse(type == "X" & grepl("Triple", savant_data$events), 3, 
                                                               ifelse(type == "X" & grepl("Home Run", savant_data$events), 4, 
                                                                      NA)))))`

**Comment by afeierman** [comment]
Awesome, that makes way more sense, thanks!

**Comment by BillPetti** [comment]
This will be available with the 0.3.3 release
