### ISSUE TITLE
Scrape_Statcast_Savant_Batter&Pitcher_All Issues

### ISSUE THREAD

**Issue by XFactor0416** [BillPetti/baseballr#191]
When attempting to use the scrape_statcast_savant_batter or pitcher_all functions over any specific dates and seasons there are a few issues that occur, but do not happen every time a scrape is run:

1. Pitch Type ends up with Pitch Type,Date which then messes up subsequent data in a row
2. Player Names end up with their numerical ID
3. Player Names are now in format of Last Name, First Name instead of First Name Last Name (This leads to issues with csv export to Excel where it does not recognize commas as delimiters and you end up with multiple columns of data in a single cell) (The name issue with commas could possibly be part of what is causing the first issue listed)
4. Player Names have accent marks which cause phonetic spelling when exporting to Excel

Package dependencies and baseballr were both up to date when these issues occurred. 

The specific event in a given scrape that is affected is different each time the data is scraped. Here are some screenshot examples of the issues:
![baseballr issue 2](https://user-images.githubusercontent.com/50809789/112570653-d6ad9400-8dbc-11eb-82f4-6bb9d1d7caf6.JPG)
![baseballr issue 3](https://user-images.githubusercontent.com/50809789/112570663-dad9b180-8dbc-11eb-95d6-33e7d4689798.JPG)
![baseballr issue](https://user-images.githubusercontent.com/50809789/112570681-e7f6a080-8dbc-11eb-85d6-623bbe3c0fcf.JPG)

If you have any questions or need further information please let me know.

**Comment by BillPetti** [comment]
Can you provide a few reproducible examples? So the code you ran that produced the results you attached? That will help.

**Comment by XFactor0416** [comment]
Sure, I should have done that to begin with sorry about that.

Running any of these will at times result in issues, for example last night I had no problems with s1 but today it has at least 2 issues when I just ran it. 
![image](https://user-images.githubusercontent.com/50809789/112664149-08137780-8e30-11eb-91eb-b9d1ebc8ff4d.png)

**Comment by BillPetti** [comment]
I can't replicate your issue. Generally, I would avoid the `scrape_statcast_savant_` functions and simply use `scrape_statcast_savant` and the `player_type` argument if you want batter-based results versus pitcher-based results.

When I run this set of code there is no difference between the two data sets and the `pitch_type` column does not show any combination of pitch type and date:

```
scrape_batter <- scrape_statcast_savant_batter_all('2015-04-05', '2015-04-08')
scrape_default <- scrape_statcast_savant('2015-04-05', '2015-04-08', player_type = 'batter')

dplyr::setdiff(scrape_batter, scrape_default)

# A tibble: 0 x 90
# … with 90 variables: pitch_type <chr>, game_date <date>, release_speed <dbl>,
#   release_pos_x <dbl>, release_pos_z <dbl>, player_name <chr>, batter <dbl>, pitcher <dbl>,
#   events <chr>, description <chr>, spin_dir <lgl>, spin_rate_deprecated <lgl>,
#   break_angle_deprecated <lgl>, break_length_deprecated <lgl>, zone <dbl>, des <chr>,
#   game_type <chr>, stand <chr>, p_throws <chr>, home_team <chr>, away_team <chr>, type <chr>,
#   hit_location <chr>, bb_type <chr>, balls <dbl>, strikes <dbl>, game_year <dbl>, pfx_x <dbl>,
#   pfx_z <dbl>, plate_x <dbl>, plate_z <dbl>, on_3b <dbl>, on_2b <dbl>, on_1b <dbl>,
#   outs_when_up <dbl>, inning <dbl>, inning_topbot <chr>, hc_x <dbl>, hc_y <dbl>,
#   tfs_deprecated <lgl>, tfs_zulu_deprecated <lgl>, fielder_2 <dbl>, umpire <lgl>, sv_id <chr>,
#   vx0 <dbl>, vy0 <dbl>, vz0 <dbl>, ax <dbl>, ay <dbl>, az <dbl>, sz_top <dbl>, sz_bot <dbl>,
#   hit_distance_sc <dbl>, launch_speed <dbl>, launch_angle <dbl>, effective_speed <dbl>,
#   release_spin_rate <dbl>, release_extension <dbl>, game_pk <dbl>, pitcher_1 <dbl>,
#   fielder_2_1 <dbl>, fielder_3 <dbl>, fielder_4 <dbl>, fielder_5 <dbl>, fielder_6 <dbl>,
#   fielder_7 <dbl>, fielder_8 <dbl>, fielder_9 <dbl>, release_pos_y <dbl>,
#   estimated_ba_using_speedangle <chr>, estimated_woba_using_speedangle <chr>,
#   woba_value <chr>, woba_denom <chr>, babip_value <chr>, iso_value <chr>,
#   launch_speed_angle <chr>, at_bat_number <dbl>, pitch_number <dbl>, pitch_name <chr>,
#   home_score <dbl>, away_score <dbl>, bat_score <dbl>, fld_score <dbl>, post_away_score <dbl>,
#   post_home_score <dbl>, post_bat_score <dbl>, post_fld_score <dbl>,
#   if_fielding_alignment <chr>, of_fielding_alignment <chr>, barrel <dbl>

> scrape_batter %>%
+   distinct(pitch_type)
# A tibble: 15 x 1
   pitch_type
   <chr>     
 1 CH        
 2 SI        
 3 FF        
 4 CU        
 5 FT        
 6 FC        
 7 KC        
 8 SL        
 9 FS        
10 KN        
11 null      
12 EP        
13 IN        
14 PO        
15 FO
```

```
scrape_batter <- scrape_statcast_savant_batter_all('2015-06-12', '2015-06-15')
scrape_default <- scrape_statcast_savant('2015-06-12', '2015-06-15', player_type = 'batter')

> dplyr::setdiff(scrape_batter, scrape_default)               
# A tibble: 0 x 90
# … with 90 variables: pitch_type <chr>, game_date <date>, release_speed <dbl>,
#   release_pos_x <dbl>, release_pos_z <dbl>, player_name <chr>, batter <dbl>, pitcher <dbl>,
#   events <chr>, description <chr>, spin_dir <lgl>, spin_rate_deprecated <lgl>,
#   break_angle_deprecated <lgl>, break_length_deprecated <lgl>, zone <dbl>, des <chr>,
#   game_type <chr>, stand <chr>, p_throws <chr>, home_team <chr>, away_team <chr>, type <chr>,
#   hit_location <chr>, bb_type <chr>, balls <dbl>, strikes <dbl>, game_year <dbl>, pfx_x <dbl>,
#   pfx_z <dbl>, plate_x <dbl>, plate_z <dbl>, on_3b <dbl>, on_2b <dbl>, on_1b <dbl>,
#   outs_when_up <dbl>, inning <dbl>, inning_topbot <chr>, hc_x <dbl>, hc_y <dbl>,
#   tfs_deprecated <lgl>, tfs_zulu_deprecated <lgl>, fielder_2 <dbl>, umpire <lgl>, sv_id <chr>,
#   vx0 <dbl>, vy0 <dbl>, vz0 <dbl>, ax <dbl>, ay <dbl>, az <dbl>, sz_top <dbl>, sz_bot <dbl>,
#   hit_distance_sc <dbl>, launch_speed <dbl>, launch_angle <dbl>, effective_speed <dbl>,
#   release_spin_rate <dbl>, release_extension <dbl>, game_pk <dbl>, pitcher_1 <dbl>,
#   fielder_2_1 <dbl>, fielder_3 <dbl>, fielder_4 <dbl>, fielder_5 <dbl>, fielder_6 <dbl>,
#   fielder_7 <dbl>, fielder_8 <dbl>, fielder_9 <dbl>, release_pos_y <dbl>,
#   estimated_ba_using_speedangle <chr>, estimated_woba_using_speedangle <chr>,
#   woba_value <chr>, woba_denom <chr>, babip_value <chr>, iso_value <chr>,
#   launch_speed_angle <chr>, at_bat_number <dbl>, pitch_number <dbl>, pitch_name <chr>,
#   home_score <dbl>, away_score <dbl>, bat_score <dbl>, fld_score <dbl>, post_away_score <dbl>,
#   post_home_score <dbl>, post_bat_score <dbl>, post_fld_score <dbl>,
#   if_fielding_alignment <chr>, of_fielding_alignment <chr>, barrel <dbl>
> 
> scrape_batter %>%
+   distinct(pitch_type)
# A tibble: 15 x 1
   pitch_type
   <chr>     
 1 FF        
 2 CU        
 3 SL        
 4 FT        
 5 FS        
 6 SI        
 7 CH        
 8 IN        
 9 KC        
10 FC        
11 PO        
12 null      
13 KN        
14 EP        
15 FO    
```

I would try using the `scrape_statcast_savant` base function and see if you still get issues. Also, have you tried building this data using the approach outlined [here](https://billpetti.github.io/2020-05-26-build-statcast-database-rstats-version-2.0/)?

**Comment by XFactor0416** [comment]
I tried the approach outlined at the link, it works for 2008 for setting up the database. It ran smoothly and I was able to get the data into the server I setup. (Took a bit of time to understand what is going on as I have little to no experience doing some of the stuff outlined in that link, I will probably struggle with the automation).

Upon attempting to automate it I am getting an error in 2009 season (I get the error if I try to do this on it's own as well):

![image](https://user-images.githubusercontent.com/50809789/112784897-bbdb5980-9020-11eb-94b3-d128589c74f5.png)

I am not really sure what the issue is or where it is exactly occurring in the dataset. For the first few functions outlined I copied what was there verbatim. The only area I changed in any of the subsequent functions was the dbConnect portions to something like statcast_db <- dbConnect(odbc::odbc(), "...").

**Comment by ChristianH00k** [comment]
Myself and a few others are experiencing similar issues that @XFactor0416 posted above, mainly different columns not being properly separated. I was able to trace the issue locally to Line 116 of the [Savant Scraper](https://github.com/BillPetti/baseballr/blob/master/R/scrape_statcast.R), which is the following line of code: `payload <- vroom::vroom(url, delim = ",")` 

I was able to get expected results when swapping that line with `payload <- readr::read_csv(url)`, but wasn't sure if it was a local versioning issue with `vroom` (though I believe I am up to date with version 1.4.0).

**Comment by BillPetti** [comment]
Investigating this and it appears the MLBAM team added three new columns to their downloads, including spin axis. Pushed a fix that I thin might fix the issue, but please test.

**Comment by BillPetti** [comment]
I've also rolled back to `read_csv`. I only saw the error occurring a few times a season, but for now I made the decision to sacrifice speed for parsing accuracy.
