### ISSUE TITLE
get_ncaa_baseball_roster issue

### ISSUE THREAD

**Issue by jdrnym** [BillPetti/baseballr#192]
The following code is returning the error: "Error: Can't recycle `..1` (size 38) to match `..2` (size 76)."

`players <- get_ncaa_baseball_roster(562, 2021)`

A random sampling of other team codes does not produce the same error. I'm only seeing it with 562.

Thanks!

**Comment by BillPetti** [comment]
This should be fixed via this [commit](https://github.com/BillPetti/baseballr/commit/f97778b976093ecddc6ee82bd58dc165f955a557).
