### ISSUE TITLE
error in scrape_statcast_savant

### ISSUE THREAD

**Issue by kfcaby** [BillPetti/baseballr#193]
Hi, I teach a sabermetrics course at West Point and have been using the baseballr package with my students to import statcast pitch level data.

This morning, we all started getting the error: "Can't transform a data frame with duplicate names" when we use the scrape_statcast_savant function (see attached).  I get the same error when I run old code that used to work.  
![error](https://user-images.githubusercontent.com/18712277/113327931-92088800-92e9-11eb-907b-6039646e9bfb.PNG)

**Comment by BillPetti** [comment]
They made some changes to the cvs return. I pushed an update this morning. Give it another try after the reinstall. Also, don't use `scrape_statcast_savant_batter`--that function is getting deprecated. Use `scrape_statcast_savant('2019-03-15', '2019-11-01', player_type = 'batter', playerid = mlbID)` instead.

Let me know if that solves things.

**Comment by kfcaby** [comment]
Thanks for your quick response!  That worked.

BTW, the baseballr package is great.  Extremely helpful for classes like mine.

**Comment by jestarr** [comment]
Quick question:  Is reinstall done via: `devtools::install_github("BillPetti/baseballr")` or should I install the `dev` branch listed?

**Comment by BillPetti** [comment]
Master, not dev branch
