### ISSUE TITLE
scrape_statcast_savant returning an error

### ISSUE THREAD

**Issue by zach-wolf** [BillPetti/baseballr#194]
When trying to run the scrape_statcast_savant() function, it returns the following error: 

`<error/rlang_error>
Can't transform a data frame with duplicate names.
Backtrace:
  1. purrr::map(...)
  2. global::.f(.x[[i]], ...)
  3. purrr:::safe_savant(...)
 13. baseballr:::scrape_statcast_savant.Date(...)
 14. baseballr::process_statcast_payload(payload)
  6. dplyr::ungroup(.)
 13. dplyr::mutate_at(., vars(one_of(cols_to_transform)), as.character)
 24. dplyr:::mutate.data.frame(.tbl, !!!funs)
 25. dplyr:::mutate_cols(.data, ...)
 26. DataMask$new(.data, caller_env())
 27. dplyr:::initialize(...)`

**Comment by BillPetti** [comment]
This should be fixed with a reinstall. See [here](https://github.com/BillPetti/baseballr/issues/193).

**Comment by zach-wolf** [comment]
Thanks for the quick response, the reinstall fixed the issue.
