### ISSUE TITLE
Issue with scrape_statcast_savant

### ISSUE THREAD

**Issue by mcanmann20** [BillPetti/baseballr#198]
Recently, the scrape_statcast_savant function has not been working for me. When I try to pull play-by-play data with code such as the following:

 pbp <- scrape_statcast_savant(start_date = "2020-07-23", end_date = "2020-10-01", playerid = 608337, player_type = "pitcher")

It yields this error:

Error: Can't transform a data frame with duplicate names.

**Comment by BillPetti** [comment]
Have you reinstalled?

**Comment by devin19** [comment]
I am having the same issue. I uninstalled and reinstalled and updated to version 0.8.4, but I continue to get the same error message.

**Comment by BillPetti** [comment]
I can't recreate the error:

<img width="936" alt="Screen Shot 2021-04-03 at 6 17 38 PM" src="https://user-images.githubusercontent.com/1923057/113492880-f6be1100-94a8-11eb-95c2-c3e41993913c.png">

Here's what I'd try:

- Reinstall using the `force = TRUE` argument to be sure you are overwriting your current install
- Shut down R and RStudio and start with a fresh session
- Ensure all related packages are up to date
- If none of this works provide a reproducible example and your session info

**Comment by devin19** [comment]
Your solution worked, I apologize for the issue. I really appreciate your help.
