### ISSUE TITLE
Error in get_pbp_mlb data

### ISSUE THREAD

**Issue by joeytitus** [BillPetti/baseballr#199]
Whenever I try to run the code to retrieve the pbp data for the mlb, i get this error:

`> get_pbp_mlb(as.Date('04/01/2021', format='%m/%d/%Y'))
Error in open.connection(con, "rb") : HTTP error 400.`

I'm not the most experienced coder, so I'm sorry if this is some error on my end.

**Comment by BillPetti** [comment]
That function takes a game_pk, not a date range. You can check the documentation [here](http://billpetti.github.io/baseballr/reference/get_pbp_mlb.html).

**Comment by joeytitus** [comment]
I see now... Sorry about that, thank you!
