### ISSUE TITLE
scrape_statcast_savant() populating of_fielding_alignment and if_fielding_alignment with NA

### ISSUE THREAD

**Issue by maxbay** [BillPetti/baseballr#200]
Running any of the scrape_statcast_savant functions populates the fielding alignment columns with NA. This is something I only noticed recently. It was returning proper characters as recently as last month, but when running the same code today, the columns were NA. I reinstalled the most recent version of baseballr (and dependencies) and that didn't resolve the issue. I also tried with multiple player IDs. Thanks!

**Comment by BillPetti** [comment]
Have you reinstalled baseballr recently?

**Comment by maxbay** [comment]
My mistake. I reinstalled with the previous version of the package already loaded. Just installed before loading the library and it's all fixed. Consider this resolved!
