### ISSUE TITLE
 pitcher_boxscore

### ISSUE THREAD

**Issue by timecsvk** [BillPetti/baseballr#201]
Hi Bill,
when I run the function "pitcher_boxscore" I am getting the following error:
"Can't subset columns that don't exist.
x Column `game_score` doesn't exist.
Run `rlang::last_error()` to see where the error occurred."

I have used the script from the help while other functions work perfectly therefore I do not know how to fix it.
Can I ask you to for help with this?

Many thanks.
Peter

**Comment by BillPetti** [comment]
Looks like they removed `game_score` from the return values. Should be fixed with a reinstall.

**Comment by timecsvk** [comment]
Thank you for a swift reply. 

But what you mean exactly by "Should be fixed with a reinstall"? 
Should I reinstall/update the package? Or you will update the new version of the package?

**Comment by timecsvk** [comment]
many thanks.
Reinstall helped and the script works perfectly.

**Comment by timecsvk** [comment]
Hi Bill,
probably I have found one more bug within function "pitcher_boxscore" and also within "batter_boxscore". I think column "team" is populating wrongly.
For example for match with game_pk = '631386': away players have teamID ='23', but it should be '116'. And home players have teamID as date 'September 27, 2020' instead of '118'. 
I believe that these columns are populating wrongly from "away_wins" and "date".

Please, can you look at it?
Many thanks in advance.
Peter

**Comment by BillPetti** [comment]
Good catch, this should be fixed now if you reinstall the package.
