### ISSUE TITLE
get_ncaa_schedule_info() returns the "RPI Ranking" Header as score and inning data...

### ISSUE THREAD

**Issue by supernole1** [BillPetti/baseballr#208]
Only for years 2019-2021.  Works fine for 2018 and beyond...
![image](https://user-images.githubusercontent.com/84671386/119263692-bbd18300-bba5-11eb-83ea-3eed49afb360.png)

**Comment by BillPetti** [comment]
Thanks for finding this. This should be fixed, reinstall baseballr and give it a try.

**Comment by TravisRPetersen** [comment]
I'm getting an error for get_ncaa_schedule_info after installing baseballr_0.8.5

get_ncaa_schedule_info(529, 2021)

`
Warning message:
“Expected 3 pieces. Missing pieces filled with `NA` in 53 rows [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, ...].”
Error: Can't recycle `..1` (size 57) to match `..2` (size 51).
Traceback:

1. get_ncaa_schedule_info(529, 2021)
2. game_result %>% filter(result != "Ppd") %>% bind_cols(game_info_url[, 
 .     c(2, 3)]) %>% select(row, slug, game_info_url)
3. select(., row, slug, game_info_url)
4. bind_cols(., game_info_url[, c(2, 3)])
5. vec_cbind(!!!dots, .name_repair = .name_repair)
6. stop_incompatible_size(x = .Primitive("quote")(structure(list(

`

**Comment by supernole1** [comment]
This worked.  thank you for the response and fix!

**Comment by saiemgilani** [comment]
This will be fixed/was fixed with the most recent PR's #230
