### ISSUE TITLE
Error Installing BaseballR

### ISSUE THREAD

**Issue by Daniel-Tucker** [BillPetti/baseballr#212]
Below is the code, along with the message returned. The package "cli" is installed and loaded. I am using R version 4.0.3.

devtools::install_github("BillPetti/baseballr")
Downloading GitHub repo BillPetti/baseballr@HEAD
These packages have more recent versions available.
It is recommended to update all of them.
Which would you like to update?

1: All                        
2: CRAN packages only         
3: None                       
4: cli (3.0.0 -> 3.0.1) [CRAN]

Enter one or more numbers, or an empty line to skip updates: 1
cli (3.0.0 -> 3.0.1) [CRAN]
Installing 1 packages: cli

  There is a binary version available but the source version is later:
    binary source needs_compilation
cli  3.0.0  3.0.1              TRUE

Do you want to install from sources the package which needs compilation? (Yes/no/cancel) Yes
installing the source package ‘cli’

trying URL 'https://cran.rstudio.com/src/contrib/cli_3.0.1.tar.gz'
Content type 'application/x-gzip' length 225589 bytes (220 KB)
==================================================
downloaded 220 KB

Warning in file(con, "r") :
  cannot open file '/var/db/timezone/zoneinfo/+VERSION': No such file or directory
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

/Library/Frameworks/R.framework/Resources/bin/INSTALL: line 34: 46518 Done                    echo 'tools:::.install_packages()'
     46519 Abort trap: 6           | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --no-echo --args ${args}

The downloaded source packages are in
	‘/private/var/folders/gh/2bzyrwxj66vc6z6287wvl_cr0000gn/T/RtmpAXqS9W/downloaded_packages’
✓  checking for file ‘/private/var/folders/gh/2bzyrwxj66vc6z6287wvl_cr0000gn/T/RtmpAXqS9W/remotesb4bd10e5bee8/BillPetti-baseballr-f4c9420/DESCRIPTION’ (610ms)
─  preparing ‘baseballr’: (553ms)
✓  checking DESCRIPTION meta-information ...
   Warning in file(con, "r") :
     cannot open file '/var/db/timezone/zoneinfo/+VERSION': No such file or directory
─  checking for LF line-endings in source and make files and shell scripts (645ms)
─  checking for empty or unneeded directories
─  building ‘baseballr_0.8.5.tar.gz’
   
Warning in file(con, "r") :
  cannot open file '/var/db/timezone/zoneinfo/+VERSION': No such file or directory
dyld: lazy symbol binding failed: Symbol not found: _utimensat
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

dyld: Symbol not found: _utimensat
  Referenced from: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libR.dylib (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib

/Library/Frameworks/R.framework/Resources/bin/INSTALL: line 34: 46556 Done                    echo 'tools:::.install_packages()'
     46557 Abort trap: 6           | R_DEFAULT_PACKAGES= LC_COLLATE=C "${R_HOME}/bin/R" $myArgs --no-echo --args ${args}
Warning messages:
1: In i.p(...) : installation of package ‘cli’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘/var/folders/gh/2bzyrwxj66vc6z6287wvl_cr0000gn/T//RtmpAXqS9W/fileb4bd5b587a02/baseballr_0.8.5.tar.gz’ had non-zero exit status

**Comment by BillPetti** [comment]
What happens if you don't update `cli`? I don't know anything about this error, but appears unrelated to `baseballr` and potentially a more general problem with `R`, Mac, and `Xcode`:

[https://community.rstudio.com/t/getting-the-following-error-while-trying-to-install-caret-package/84993/3](https://community.rstudio.com/t/getting-the-following-error-while-trying-to-install-caret-package/84993/3)

[https://github.com/tidyverse/lubridate/issues/928](https://github.com/tidyverse/lubridate/issues/928)

**Comment by saiemgilani** [comment]
Please try with the new version of the package and if issues persist, please open a new issue. I am going to close this issue
