### ISSUE TITLE
Installation Failing But Not Raising Error

### ISSUE THREAD

**Issue by NerdyBaseballDude** [BillPetti/baseballr#213]
Hello,

I have an issue similar to another in this list. I have all the dependent packages installed correctly. However, when I go to download the package, I don't get an error, but I only get 2/5 checkmarks of the download and it fails. Any help is greatly appreciated. This is what I get in the console:

```
Downloading GitHub repo BillPetti/baseballr@HEAD
√  checking for file 'C:\Users\MadisonDC\AppData\Local\Temp\RtmpeSkHuL\remotes246c7ffe330b\BillPetti-baseballr-f4c9420/DESCRIPTION' (356ms)
-  preparing 'baseballr': (738ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'baseballr_0.8.5.tar.gz'

**Comment by BillPetti** [comment]
I can't replicate this behavior. I see the same behavior, but it does not fail. Can you provide more output as well as your session info?

**Comment by NerdyBaseballDude** [comment]
Thanks for reaching out. I was actually able to install the package by downloading it as a .Zip file and uploading it into R that way, but I'll still share my code for anyone else that might be struggling with the same issue.

Here's my session info:
![image](https://user-images.githubusercontent.com/87952981/127161774-8c991177-feba-421d-98f6-f62a037ee109.png)

This is what I run:
```
library(devtools)
install.packages('BillPetti/baseballr)
```
I then get this in the console:
```
Downloading GitHub repo BillPetti/baseballr@HEAD
√  checking for file 'C:\Users\MadisonDC\AppData\Local\Temp\RtmpiO60go\remotes1ee02ae87f98\BillPetti-baseballr-3a52f54/DESCRIPTION' ...
-  preparing 'baseballr': (780ms)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'baseballr_0.8.5.tar.gz'
```
However, after it ran (and before I installed the package as a .zip), I did ```library(baseballr)``` and R did not recognize the package.

I hope this helps.

**Comment by saiemgilani** [comment]
I believe you're having trouble because that is not how you install a package with `devtools`. 
All of the following code you can run in the console of RStudio or in a `.R` script
```
devtools::install_github("billpetti/baseballr")
```
From the README of the current version of the `baseballr` repo:
**Option 1: Using the `pacman` package**
```
# You can install using the pacman package using the following code:
if (!requireNamespace('pacman', quietly = TRUE)){
  install.packages('pacman')
}
pacman::p_load_current_gh("BillPetti/baseballr")
```

**Option 2: Using `devtools`**
```
# if you would prefer devtools installation
if (!requireNamespace('devtools', quietly = TRUE)){
  install.packages('devtools')
}
# Alternatively, using the devtools package:
devtools::install_github(repo = "BillPetti/baseballr")
```

I am going to close this issue, if you continue to have problems, please open a new issue.
