### ISSUE TITLE
R version 3.3.3

### ISSUE THREAD

**Issue by Arias29** [BillPetti/baseballr#22]
This is the version I am currently running but when trying to install baseballr it says that it is unavailable for this version. Is this just a matter of time before it will be available or do I have to downgrade to a previous version?

**Comment by BillPetti** [comment]
That's odd, I am running `R version 3.4.0 (2017-04-21)` and it installs fine for me. Can you provide `session_info`?

**Comment by Arias29** [comment]
> require(devtools)

Loading required package: devtools

> library("devtools", lib.loc="C:/Program Files/R/R-3.3.3/library")

> install.packages("BillPetti/baseballr")

Warning in install.packages :

  package ‘BillPetti/baseballr’ is not available (for R version 3.3.3)

 

 

Session info
----------------------------------------------------------------------------
------------

setting  value                       

 version  R version 3.3.3 (2017-03-06)

system   i386, mingw32               

 ui       RStudio (1.0.136)           

 language (EN)                        

 collate  English_United States.1252  

 tz       America/Chicago             

 date     2017-05-03                  

 

Packages
----------------------------------------------------------------------------
----------------

package  * version date       source        

 devtools * 1.12.0  2016-06-24 CRAN (R 3.3.3)

digest     0.6.12  2017-01-27 CRAN (R 3.3.3)

memoise    1.1.0   2017-04-21 CRAN (R 3.3.3)

withr      1.0.2   2016-06-20 CRAN (R 3.3.3)

**Comment by BillPetti** [comment]
You are trying to install from CRAN (`install.packages("BillPetti/baseballr"`). You need to use the `install_github` function from the `devtools` package: 

`install_github("BillPetti/baseballr")`

**Comment by Arias29** [comment]
Great! Thanks!
