### ISSUE TITLE
"no such file or directory'

### ISSUE THREAD

**Issue by brywaz** [BillPetti/baseballr#224]
![image](https://user-images.githubusercontent.com/89617698/138143012-4e1f0ed9-18ee-4800-8e4d-0ce7a196c72f.png)

Any help with why this isn't working for me? I'm on windows 10.

**Comment by BillPetti** [comment]
You need to indicate a full path directory for the `path_to_directory` argument.

**Comment by saiemgilani** [comment]
Closed by #255
