### ISSUE TITLE
Get schedule for NCAA not working for 2022

### ISSUE THREAD

**Issue by TravisRPetersen** [BillPetti/baseballr#236]
**Describe the bug**

It looks like this is due to the fact that the Attendance column is not populated if the games have not been played yet.

2021 Schedule: https://stats.ncaa.org/teams/509032?utf8=%E2%9C%93&year_id=509032&sport_id=526415&commit=Submit&org_sport_name=&org_id=
2022 Schedule: https://stats.ncaa.org/teams/526415?utf8=%E2%9C%93&year_id=526415&sport_id=509032&commit=Submit&org_sport_name=&org_id=

**To Reproduce**

Notebook: https://colab.research.google.com/drive/1s05_p-j7qH46tSxXCoNMw9vVm6IHbaWv?usp=sharing

**Expected behavior**

Schedule pulled without scores/attendance if games haven't been played yet.

**Screenshots**

![image](https://user-images.githubusercontent.com/13895464/151046752-29c5b2bd-ebc8-4e71-94af-7fd0272aec9f.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by saiemgilani** [comment]
Oops, will fix quickly, but there are so many open PRs on the dev branch that need to be merged that it might require serious git mastery or me breaking the prescribed git flow to update quickly

**Comment by BillPetti** [comment]
Sorry, I am the bottleneck on the dev branch. Never got to review the PRs during the holidays and have been buried since the new year. I will make this a priority to get to.

**Comment by saiemgilani** [comment]
Though I'm seeing that beyond that attendance column the real culprit is the season id's not being populated for 2022 causing it to null out. I will write something that circumvents the necessity of using internal reference data that must be updated by the user with the package. I.e. baseballr-data

**Comment by saiemgilani** [comment]
Just as a comment, as of version 1.0.2, this function is working altogether much better, worth updating from master
