### ISSUE TITLE
Spring Training and Playoffs in Savant URL

### ISSUE THREAD

**Issue by jrhessey** [BillPetti/baseballr#24]
Can you change GT=R%7C to GT=R%7CPO%7CS%7C so you can pull playoff and spring training data as well if those games fall within the date range?  Thanks!

**Comment by BillPetti** [comment]
I can, but may be a little bit. Will try to get to it soon.

**Comment by BillPetti** [comment]
Thanks to @keberwein for making this change so quickly!

**Comment by keberwein** [comment]
LOL, I was working on another project and just happened to see it. Cheers to short attention spans!
