### ISSUE TITLE
URL column issue with get_ncaa_schedule_info

### ISSUE THREAD

**Issue by kelvinervais** [BillPetti/baseballr#244]
When trying to use get_ncaa_schedule_info, I noticed that the url for each game remained the same despite the rest of the information changing.  What I mean by this is the url for the game stays the same throughout the entire season.  I tried with University of Houston, UIC, and Vandy.  

EX:
TEAM <- get_ncaa_schedule_info(teamid = id, year = year)
TEAM$game_info_url

I would expect to see different URL's for each game however they all appear to be the same.  I was hoping to use these URL's to scrape a season's worth of data.

<img width="400" alt="Screen Shot 2022-02-09 at 12 45 22 AM" src="https://user-images.githubusercontent.com/72356137/153158492-4783ae68-922f-414f-acf4-b145fea287b9.png">

**Comment by saiemgilani** [comment]
i'm a clown, lemme fix it, gimme a day

**Comment by saiemgilani** [comment]
Should be fixed as of v1.0.2 from master.
