### ISSUE TITLE
Missing column "barrel" statcast_search_pitchers

### ISSUE THREAD

**Issue by zivoderjm** [BillPetti/baseballr#245]
**Is your feature request related to a problem? Please describe.**
In previous versions of baseballr, this function pulled in 93 columns. I noticed that the column "barrel" is no longer included based on previous files that I have saved in the past.

**To Reproduce**
test <- baseballr::statcast_search_pitchers("2021-04-01", "2021-10-03", 642547)

**Describe the solution you'd like**
I was hoping that the original 93 columns would be pulled that includes the now missing column called "barrel".

**Comment by saiemgilani** [comment]
So that's my doing. I really didn't know people were using that column like that. You can create the column by running the dataframe through the function `code_barrel(df)`

**Comment by saiemgilani** [comment]
Erg. Yeah I dunno. I will dig into it soonish

**Comment by BillPetti** [comment]
They changed their column labeling at some point and the function didn't get updated. `hit_angle` and `hit_speed` need to have 'hit' swapped for 'launch' and it will work
