### ISSUE TITLE
get_retrosheet_data not working properly

### ISSUE THREAD

**Issue by gdrod12** [BillPetti/baseballr#246]
**Describe the bug**
When I try using the get_retrosheet_data function, the all2018.csv file turns into a 1 column, 0 variable file. When I run the function, I get "Could Not Find C:\Users\gadar\OneDrive\Documents\retrosheet\download.folder\*.EDN and
"Could Not Find C:\Users\gadar\OneDrive\Documents\retrosheet\download.folder\*.EDA . This is almost certainly an issue on my end but I cannot figure out what it is.

**To Reproduce**
get_retrosheet_data(path_to_direct="~/retrosheet/", years_to_acquire=2018) 

**Expected behavior**
Expected to get all of the pbp data for 2018.
I'm using windows. I saw one fix in which I put the cwevent.exe into the unzipped folder, and that actually took away one of their errors but the result was the same.

**Comment by BillPetti** [comment]
Will look into it. When I originally built the function I did it using Mac OS and borrowed some code which was also based on Mac, so it may be we need to add some code to identify the OS and based on that make some changes.

**Comment by saiemgilani** [comment]
Closed by #255
