### ISSUE TITLE
Error in standings_on_date_bref()

### ISSUE THREAD

**Issue by Chris-Engelhardt** [BillPetti/baseballr#25]
standings_on_date_bref() fails with an error.

My code: 

`library(baseballr)`
`standings_on_date_bref("2015-08-04", "AL East")`

Error in setNames(., table_names[ind]) : 
  'names' attribute [1] must be the same length as the vector [0]

Running baseballr version 0.3.2 on Windows 10 with R 3.3.3.

**Comment by BillPetti** [comment]
Looks like they changed the site structure. Will have to fix the function.

**Comment by Chris-Engelhardt** [comment]
Thanks, Bill.

**Comment by Chris-Engelhardt** [comment]
As you might know, other functions that use baseball-reference.com are broken as well (e.g., team_consistency()).

**Comment by BillPetti** [comment]
Just pushed a fix, let me know if it works. Will look into the other BRef functions. Thanks for the heads up.

**Comment by Chris-Engelhardt** [comment]
Yes, standings_on_date_bref() works now. Thanks for your quick attention -- I have several people here at CARFAX excited about baseballr.

**Comment by BillPetti** [comment]
Excellent!
