### ISSUE TITLE
Attempting to acquire retrosheet data from 2015

### ISSUE THREAD

**Issue by DailyAdamG** [BillPetti/baseballr#258]
Using the following code to get retrosheet data from 2015:

get_retrosheet_data(path_to_directory = "~/Desktop/retrosheet", 
                    years_to_acquire = 2015)

And seeing the following error:

Error in data.table::fread(paste0("all", year, ".csv"), col_names = FALSE) : 
  unused argument (col_names = FALSE)

It looks like the retrosheet files are being added to the unzipped folder, but it is returning an empty all2015 csv file.

**Comment by saiemgilani** [comment]
Please update your package from CRAN using:
```r
install.packages("baseballr)
```
Then try again

**Comment by DailyAdamG** [comment]
I updated the package, but now I'm getting a different error message:

Please install the Chadwick CLI program from:
https://github.com/chadwickbureau/chadwick/releases

I'm confused, because I'm fairly certain that I have the program in my
downloads?

Thank you so much for the timely response by the way!

**Comment by saiemgilani** [comment]
it needs to be available on your PATH variable for it to be recognized from the shell

For example, I have all of my Chadwick CLI programs stored in the folder: `C:\Retrosheet\common\programs`

So I added that folder to my pc's `Path` environment variable

**Comment by DailyAdamG** [comment]
I'm attempting your solution, but I think I am getting it wrong still. Bear with me I'm still new to this. I have added the Chadwick files in my folder path here:

![Picture1](https://user-images.githubusercontent.com/57848406/165566447-9a61ca78-842b-4769-a4e4-8fb2464e2bd9.png)

However, now I'm getting a different error message in R and I'm still getting an empty table:

Error in setnames(x, value) : 
  Can't assign 97 names to a 0 column data.table
In addition: Warning messages:
1: In shell(paste(paste("cwevent -y", year, "-f 0-96 -q"), paste(year,  :
  'cwevent -y 2015 -f 0-96 -q 2015*.EV* > all2015.csv' execution failed with error code 1
2: In data.table::fread(paste0("all", year, ".csv"), header = FALSE) :
  File 'all2015.csv' has size 0. Returning a NULL data.table.

I'm sure it's something simple on my end and I'm just not understanding the core concept of my error.

**Comment by saiemgilani** [comment]
Oh delete the file. Try again

**Comment by DailyAdamG** [comment]
I deleted the file and got the same error message.

**Comment by saiemgilani** [comment]
I'll get back to ya

**Comment by saiemgilani** [comment]
Yeah I am having some trouble when writing to disk. However, if you do not set the path directory, it should work as it is to produce you two tables, one for events, the other for rosters. I will look into this further at some point or may just do all the conversions and make it loadable.

**Comment by BillPetti** [comment]
I've tried recreating this and I haven't been able to so far. I've tried this with both 2015 and 2020 data.

```
R version 4.0.3 (2020-10-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 10.16

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] baseballr_1.2.0

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.7         pillar_1.6.0       compiler_4.0.3     tools_4.0.3       
 [5] lubridate_1.7.9.2  jsonlite_1.7.2     lifecycle_1.0.0    tibble_3.1.0      
 [9] gtable_0.3.0       pkgconfig_2.0.3    rlang_0.4.10       cli_3.0.1         
[13] rstudioapi_0.13    DBI_1.1.1          curl_4.3           dplyr_1.0.3       
[17] httr_1.4.2         stringr_1.4.0      xml2_1.3.2         janitor_2.1.0     
[21] generics_0.1.0     vctrs_0.3.7        grid_4.0.3         tidyselect_1.1.0  
[25] glue_1.4.2         snakecase_0.11.0   data.table_1.14.1  R6_2.5.0          
[29] fansi_0.4.2        ggplot2_3.3.3      purrr_0.3.4        tidyr_1.1.2       
[33] magrittr_2.0.1     scales_1.1.1       ellipsis_0.3.1     assertthat_0.2.1  
[37] rvest_1.0.1        colorspace_2.0-0   utf8_1.2.1         stringi_1.5.3     
[41] RcppParallel_5.1.4 munsell_0.5.0      crayon_1.4.1      
```

**Comment by DailyAdamG** [comment]
I got it to work! I put cwevent into the unzipped folder and it worked for me.

**Comment by saiemgilani** [comment]
So one other thing I did which has made life a bit easier was adding the path to cwevent to the PATH variable I have stored in my .Renviron file. I dunno if I was always supposed to be doing this but hm, ill document it inbthe near future. Closing issue.
