### ISSUE TITLE
mlb_player_game_stats()

### ISSUE THREAD

**Issue by thaydye** [BillPetti/baseballr#259]
Hi,

When I run the mlb_player_game_stats() function, it returns a tibble with all the column names in the first column. There must be a syntax error. See attached picture.

![image](https://user-images.githubusercontent.com/107659345/174202483-1f72de4a-f119-4c95-8b93-0c0b062340fe.png)

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BillPetti** [comment]
Can you provide a reproducible example of the error please?

**Comment by saiemgilani** [comment]
https://billpetti.github.io/baseballr/reference/mlb_player_game_stats.html

```
mlb_player_game_stats(person_id = 605151, game_pk = 531368)
```

No idea what's going on here but will look into it

**Comment by saiemgilani** [comment]
And by that I meant, thank you @thaydye it has been fixed on the master branch, retry installing from GitHub and you'll be good
