### ISSUE TITLE
bref_team_results() returns no data

### ISSUE THREAD

**Issue by darrenpage15** [BillPetti/baseballr#267]
The bref_team_results() function results in the error message: "Invalid arguments or no team results data available!"

Example code: bref_team_results("MIN", 2022)

Other functions that pull data from baseball reference fail as well.

**Comment by rdelrossi** [comment]
No problem with `bref_team_results("MIN", 2022)` on my end, @darrenpage15. Have you tried updating to the latest version or reinstalling altogether?

**Comment by saiemgilani** [comment]
On most recent release, we've added a 5 second rest for all calls to baseball-reference functions to comply with their scraping guidelines announced recently. While I believe all 403 and 429 issues should resolve themselves within 24 hours or so according to their new policy. As a result of complying, these 403/429 issues will stop happening, even if the time to resolve the query will take ~5x amount of time as it used to.
