### ISSUE TITLE
scrape_statcast_savant

### ISSUE THREAD

**Issue by rcarden71** [BillPetti/baseballr#270]
**Describe the bug**

///Receive error message when trying to collect 7 days' worth of data: "Downloaded 10252 bytes...HTTP error 504.Error in value[[3L]](cond) : No payload acquired"

**To Reproduce**

///Syntax used ------------>   refreshdata <- rbind(scrape_statcast_savant("2022-04-07", "2022-04-13"))

**Expected behavior**

///All statcast data from 4/7 - 4/13  for 2022 to be collected and placed in data frame 'refreshdata'

**Screenshots**

**Desktop (please complete the following information):**

///Windows 11

**Smartphone (please complete the following information):**

**Additional context**

**Comment by BillPetti** [comment]
This is a known issue with the Savant site, not `baseballr`. See [here](https://twitter.com/baseball_tools/status/1572553469172805632?s=46&t=Zzfa_2zdpDwwtvJ2G5rQ6w).
