### ISSUE TITLE
Can't use Player Lookup functions

### ISSUE THREAD

**Issue by baldrige** [BillPetti/baseballr#283]
All of the player lookup functions (playerid_lookup, playername_lookup) return a similar error: 

Error in curl::curl_download(input, tmpFile, mode = "wb", quiet = !showProgress) : 
  HTTP error 404.

I am running RStudio on Windows with R 4.2.2, baseballr 1.4.0, and curl 5.0.0. Thanks for any thoughts you might have!

**Comment by camdenk** [comment]
The repository holding that data changed its structure about a week ago. So, the file that we're attempting to load to allow you to lookup a player doesn't exist anymore.

Thanks for bringing this to our attention!

**Comment by mdemarte21** [comment]
Do y'all have an estimated timeline for when there will be a solution to this? Just asking as I was using it for a project I was working on!

**Comment by saiemgilani** [comment]
> Do y'all have an estimated timeline for when there will be a solution to this? Just asking as I was using it for a project I was working on!

Asap. I don't like what they did but I'll figure it out tn
