### ISSUE TITLE
Error getting the latest version of baseballr

### ISSUE THREAD

**Issue by kylemckelvey16** [BillPetti/baseballr#286]
I'm having trouble getting the latest version of baseballr. I used 

devtools::install_github("BillPetti/baseballr", ref = "development_branch")

When asked to update certain packages, I tried updating All, none, and just the CRAN ones and got the same error each time (below)

![image](https://user-images.githubusercontent.com/122929781/217579306-8539250d-c72c-4068-af78-7e1480a03e7f.png)

I'm running RStudio on Windows with R 4.2.2

**Comment by camdenk** [comment]
Can you try updating the {vctrs} package and then try again?

**Comment by kylemckelvey16** [comment]
Okay that worked. I had to remove and reinstall vctrs and purrr, but updating in the prompt for updating wouldn't work.

**Comment by camdenk** [comment]
Glad that worked!
