### ISSUE TITLE
ncaa_schedule_info() Not working

### ISSUE THREAD

**Issue by williambjames** [BillPetti/baseballr#289]
Function returns an error regarding a variable `sched`:

Error in ncaa_schedule_info(teamid = 433, year = 2021) : 
  object 'sched' not found

**Comment by camdenk** [comment]
Hello!

Which version of the baseballr are you using?

**Comment by williambjames** [comment]
> 

1.5.0

**Comment by saiemgilani** [comment]
Some kinks I've been actively working through. The schedule function on the most recent push of the development branch is slow, needs rests, but now allows proxies. Will take a look tomorrow

**Comment by saiemgilani** [comment]
Please reinstall the package from the development branch and use the following code:
```r
baseballr::ncaa_schedule_info(teamid = 433, year = 2021)
```

I have renamed all the `ncaa_*()` functions which use `teamid` to use `team_id` now for consistency and it was kinda crazy that we were just using teamid in the first place imo? Also, there is no more `school_*` variables now, they're just `team_id` and `team_name`

**Comment by williambjames** [comment]
Thanks! Working great now. Much appreciated!
