### ISSUE TITLE
playerid_lookup gets 404 error

### ISSUE THREAD

**Issue by jskv** [BillPetti/baseballr#291]
> playerid_lookup("Ohtani")

[100%] Downloaded 14 bytes...
Error in curl::curl_download(input, tmpFile, mode = "wb", quiet = !showProgress) : 
 HTTP error 404.
> playername_lookup("Ohtani")

Error in curl::curl_download(input, tmpFile, mode = "wb", quiet = !showProgress) : 
  HTTP error 404.

**Comment by camdenk** [comment]
I believe this is the same error raised in #283. The file structure for where the IDs were coming from has changed which is now accounted for in newer versions of baseballr. 

Can you run `devtools::install_github("BillPetti/baseballr", ref = "development_branch")` and then try again?

**Comment by jskv** [comment]
This does solve the error, thank you! I apologize for the double post.

**Comment by camdenk** [comment]
All good! Glad this resolved it for you.
