### ISSUE TITLE
fg_team_batter function not working

### ISSUE THREAD

**Issue by Dexterdandi** [BillPetti/baseballr#293]
Using baseballr version 1.5.0 with R version 4.2.0:

fg_team_batter(2022, 2022, qual = 0) does not give any result while other commands work perfectly fine like bref_daily_batter("2022-08-01", "2022-10-03") 

Error message:
2023-03-17 15:01:00: Invalid arguments or no batter leaders data available!
Error in fg_team_batter(2022, 2022, qual = 0) : 
  object 'leaders' not found

**Comment by camdenk** [comment]
It looks like the underlying code is referencing something that doesn't exist anymore. FanGraphs might've switched something around on their end. 

We'll take a look and come up with an answer/fix soon!
