### ISSUE TITLE
team_results_bref Issues

### ISSUE THREAD

**Issue by gregalytics** [BillPetti/baseballr#30]
The following issues arise in team_results_bref:

1) After every 50 games, the headers appear as a row of data, which should not be included
2) Column 4 is labelled ".1". 
3) Column 5 H_A only shows "H"
4) Result included -wo for Walkoffs. 

I have tried using exports from Baseball-Reference's team page myself and have had trouble, so these issues are totally understandable! This package is awesome, thanks for helping the baseball community so much.

**Comment by BillPetti** [comment]
Thanks. Looks like some things moved around on their end. All but #4 was addressed (should work on reinstall)--want to leave the walk off indicator their in case people find it useful and don't want to change the shape of the result with a new column, at least not right now.

**Comment by Mattf18** [comment]
I'm having an issue using the ncaa_scrape function. I'm able to get the data for years prior to 2019, but when I run the following code:

IrvinePitch19 <- ncaa_scrape(109, 2019, type = "pitching") %>% filter(Pos == "P") %>% select(year:SO)

I get the following response:

Error in open.connection(x, "rb") : HTTP error 404.


Any help would be greatly appreciated. Thank you for all of your help and this package, it's completely changed the way I analyze the game.
