### ISSUE TITLE
ind argument returns error in the fg_pitcher_leaders function

### ISSUE THREAD

**Issue by aaronmorrisNC** [BillPetti/baseballr#305]
Hello,

I am using RStudio version 2023.06.0 Build 421 and baseballR version 1.5.0.  When running the following function data is returned and all is well

fg_pitcher_leaders (2022, 2024, league = "all", pitcher_type = "sta", ind = 1)

However, if I change the ind argument to "0" as follows

fg_pitcher_leaders (2022, 2024, league = "all", pitcher_type = "sta", ind = 0)

I get the following error

2023-06-15 13:34:18: Invalid arguments or no pitcher leaders data available!

![image](https://github.com/BillPetti/baseballr/assets/112770416/0e8a3e2a-5ccf-4f84-9b62-d613a1817aa8)

**Comment by camdenk** [comment]
I believe the error is caused by the argument attempting to pull data from the 2024 season, which would be empty at this point.

**Comment by aaronmorrisNC** [comment]
I dug a bit deeper and modified that pitcher_type argument in addition to the ind argument.

fg_pitcher_leaders(2022, 2024, league = "all", pitcher_type = "rel", ind = 0)
fg_pitcher_leaders(2022, 2024, league = "all", pitcher_type = "sta", ind = 0)

The first command doesn't error whereas the second does.  So I don't think it is an issue with the 2024 value unless I am not seeing something.

![image](https://github.com/BillPetti/baseballr/assets/112770416/d5e7c5a9-4d04-43c2-a500-3c584e299496)

**Comment by camdenk** [comment]
What's the end goal for this function call? 

The data returned by the function seems to match what it would look like when directly input on the FanGraphs site, except for returning the error for Alcantara's single row when looking at SPs.

**Comment by aaronmorrisNC** [comment]
So it's my understanding that the ind = 0 argument aggregates the data for all seasons.  I have a workaround but wanted to bring it to the attention of the authors.

**Comment by aaronmorrisNC** [comment]
Appreciate the help @camdenk!  I can confirm that it works as intended using your suggestion.

**Comment by aaronmorrisNC** [comment]
Appreciate the help @camdenk.  I can confirm your suggestion works as intended.
