### ISSUE TITLE
team_consistancy error

### ISSUE THREAD

**Issue by jrhessey** [BillPetti/baseballr#31]
team_consistency(2017)
Error in team_results_bref(.$Tm, .$year) : object 'col_names' not found

I'm getting the error above when trying the team_consistency function

**Comment by BillPetti** [comment]
Missed some code in a fox for `team_results_bref`. Should be fixed now.

**Comment by BillPetti** [comment]
Whoops, one more thing to fix. Hold tight.

**Comment by jrhessey** [comment]
Thanks Bill!

**Comment by BillPetti** [comment]
Okay, on reinstall it should work.

**Comment by BillPetti** [comment]
Did this work, @jrhessey?
