### ISSUE TITLE
package pulled from CRAN

### ISSUE THREAD

**Issue by beanumber** [BillPetti/baseballr#315]
`baseballr` has been archived by CRAN. 

https://cran.r-project.org/web/packages/baseballr/index.html

Are there plans to get this back on CRAN? Jim and I need to know since we are planning to reference the package substantially in [the 3rd edition of *ABWDR*](https://beanumber.github.io/abdwr3e/). It will make our lives considerably easier if `baseballr` is back on CRAN.

**Comment by saiemgilani** [comment]
oh fuckin' whattttt. Yes, I'm on it. I never saw the email and I have no idea why. Do not worry, I will immediately get to it. My sincerest apologies and please do use it. One of my primary goals of putting baseballr on CRAN was explicitly for you to use in any of the books you write.

**Comment by CarlColglazier** [comment]
Seeing this right now too. Hope all is well.

**Comment by saiemgilani** [comment]
It's already being done. I just have a couple functions to push. I had not forgotten about this, nor our 60 day deadline for the SportsAnalytics topic removal

**Comment by saiemgilani** [comment]
It's being submitted today. I would have submitted it a couple weeks ago but CRAN was on holiday

**Comment by beanumber** [comment]
Great! Glad to hear it!

**Comment by saiemgilani** [comment]
I expect to hear back in the next day or two after resubmission/correcting some notes they made

**Comment by saiemgilani** [comment]
> Did you hear back from CRAN?

Just heard back, it should be on CRAN now.

![Screenshot_20240116_090117_Gmail](https://github.com/BillPetti/baseballr/assets/25425933/b1e2f320-2300-4e1e-8eac-54a8ea3235b4)

[On CRAN!](https://cran.r-project.org/web/packages/baseballr/index.html)

**Comment by beanumber** [comment]
Great news!
