### ISSUE TITLE
New functions?

### ISSUE THREAD

**Issue by keberwein** [BillPetti/baseballr#32]
Hey @BillPetti I quietly dropped [this package](https://github.com/keberwein/baseballDBR) on CRAN today. Basically, just a method to download tables from the Baseball Databank, because I got tired of Lahman always being out of date. There's no real overlap with your package but there are a couple of functions I thought you would find useful. Feel free to use them.

* Scraper for the Chadwick Bureau's Baseball Databank Git repo.
https://github.com/keberwein/baseballDBR/blob/master/R/get_bbdb.R

* wOBA values based on the Lahman tables. I ported [Tom Tango's](http://www.insidethebook.com/ee/index.php/site/article/woba_year_by_year_calculations/) SQL over to an R function.
https://github.com/keberwein/baseballDBR/blob/master/R/woba_values.R

* FIP values based on a similar method.
https://github.com/keberwein/baseballDBR/blob/master/R/fip.R

I'll probably start promoting the package next week sometime. Anyhoo, feel free to close this issue, just wanted to open an invitation to use any of this stuff if you want.

**Comment by BillPetti** [comment]
Cool! Sorry, I totally missed this when you first posted it. Will have a looksee.

**Comment by keberwein** [comment]
LOL, no problem. Not really an issue anyway. Like to keep things tidy!
