### ISSUE TITLE
Name/Column Assignment

### ISSUE THREAD

**Issue by burtmaclinmilb** [BillPetti/baseballr#331]
scrape_statcast_savant_pitcher_all returned this error:

 [100%] Downloaded 11403481 bytes...
Error in setnames(x, value) : 
  Can't assign 92 names to a 94 column data.table

Thank you for your time!

**Comment by camdenk** [comment]
Download the dev version with `devtools::install_github("BillPetti/baseballr")` and this should be fixed!
