### ISSUE TITLE
Statcast Search (scrape_statcast_savant) Error: Can't assign 92 names to a 94-column data.table

### ISSUE THREAD

**Issue by admiralrpi** [BillPetti/baseballr#334]
**Describe the bug**
After 2 new fields added, function will not scrape the columns correctly.

**To Reproduce**

**Expected behavior**

**Screenshots**

![Statcast function error](https://github.com/BillPetti/baseballr/assets/130490362/4719204c-ca21-4f77-b934-e452cb6029ff)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by camdenk** [comment]
Download the dev version with devtools::install_github("BillPetti/baseballr") and this should be fixed!

**Comment by admiralrpi** [comment]
Thank you
