### ISSUE TITLE
savant scrape no longer working

### ISSUE THREAD

**Issue by jrhessey** [BillPetti/baseballr#34]
I did some testing in the savant batter all scrape function and found there is a new parameter (hfC=)

Update the url from

https://baseballsavant.mlb.com/statcast_search/csv?all=true&hfPT=&hfAB=&hfBBT=&hfPR=&hfZ=&stadium=&hfBBL=&hfNewZones=&hfGT=R%7CPO%7CS%7C=&hfSea=&hfSit=&player_type=batter&hfOuts=&opponent=&pitcher_throws=&batter_stands=&hfSA=&game_date_gt=",start_date,"&game_date_lt=",end_date,"&team=&position=&hfRO=&home_road=&hfFlag=&metric_1=&hfInn=&min_pitches=0&min_results=0&group_by=name&sort_col=pitches&player_event_sort=h_launch_speed&sort_order=desc&min_abs=0&type=details&

to

https://baseballsavant.mlb.com/statcast_search/csv?all=true&hfPT=&hfAB=&hfBBT=&hfPR=&hfZ=&stadium=&hfBBL=&hfNewZones=&hfGT=R%7CPO%7CS%7C&hfC=&hfSea=&hfSit=&player_type=batter&hfOuts=&opponent=&pitcher_throws=&batter_stands=&hfSA=&game_date_gt=",start_date,"&game_date_lt=",end_date,"&team=&position=&hfRO=&home_road=&hfFlag=&metric_1=&hfInn=&min_pitches=0&min_results=0&group_by=name&sort_col=pitches&player_event_sort=h_launch_speed&sort_order=desc&min_abs=0&type=details&

and I think that should fix it, at least it did in my fork...

**Comment by BillPetti** [comment]
That's a great catch. I have been futzing with it for a few days and couldn't figure it out. I've updated all four `scrape_statcast` functions with the new term. Thanks!

**Comment by BillPetti** [comment]
Turns out there's been more of a change. You now have to have `Sea` field set in your query, even when going across seasons. For now, the functions will only allow queries across the same season. That seems to be the most reliable fix.
