### ISSUE TITLE
statcast_search pitcher error:     Error in setnames(x, value) Can't assign 92 names to a 94 column data.table

### ISSUE THREAD

**Issue by snoopryan123** [BillPetti/baseballr#340]
**Describe the bug**
statcast_search for daily pitching data is getting an error
Error in setnames(x, value) Can't assign 92 names to a 94 column data.table

<img width="881" alt="Screenshot 2024-05-26 at 11 58 37 PM" src="https://github.com/BillPetti/baseballr/assets/30908018/5c73f67d-b159-4433-bebd-fb52996668a9">

**Comment by MetruvianMan** [comment]
Same issue for player_type = "batter"

**Comment by MetruvianMan** [comment]
> **Describe the bug** statcast_search for daily pitching data is getting an error Error in setnames(x, value) Can't assign 92 names to a 94 column data.table
> 
> <img alt="Screenshot 2024-05-26 at 11 58 37 PM" width="881" src="https://private-user-images.githubusercontent.com/30908018/333998823-5c73f67d-b159-4433-bebd-fb52996668a9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NzUzNjksIm5iZiI6MTcxNzQ3NTA2OSwicGF0aCI6Ii8zMDkwODAxOC8zMzM5OTg4MjMtNWM3M2Y2N2QtYjE1OS00NDMzLWJlYmQtZmI1Mjk5NjY2OGE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA0MjQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdkMTg3YzhhYzNmOWNlMTE3ZTYyZmYzMjExNmVjODE3MmVlOWY5MWMzN2ZlMDJhODY5ZjA0NTAyNjVjZTBlZjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Qa9GIqTaKothos-5jxYe1qesdI3YgCuc3sowPuqgiWg">

I installed the dev tools version and restarted RStudio and that resolved the issue.
