### ISSUE TITLE
fg_batter_leaders

### ISSUE THREAD

**Issue by jkenney1123** [BillPetti/baseballr#347]
The function call for fg_batter_leaders keeps giving me a leaders not found error

fg_batter_leaders(startseason = 2015, endseason = 2015, qual = 400)

Error in fg_batter_leaders(startseason = 2015, endseason = 2015, qual = 400) : 
  object 'leaders' not found

**Comment by BushJohnson122** [comment]
try reinstalling baseballr, worked for me today

if you want to use it across multiple seasons you should be able to do it with this
purrr::map_df(.x = c(2003:2023),
                       ~baseballr::fg_batter_leaders(startseason = .x, endseason = .x))

**Comment by jkenney1123** [comment]
Great it works now and thanks for the multiple season code it was exactly what I needed.
