### ISSUE TITLE
Run scoring

### ISSUE THREAD

**Issue by statsbylopez** [BillPetti/baseballr#36]
I know this is likely infeasible, but grabbing the score-state for each pitch (number of runs for home team, number of runs for the away team) in the `scrape_statcast_savant_batter_all` would be awesome.

**Comment by LeeZee1** [comment]
or, even the score-state for each inning as in retrosheet would be awesome.

**Comment by BillPetti** [comment]
This was added by the Statcast team as part of the Baseball Savant download. New functions for calculating run expectancy and for creating variables for runs scored as a result of a given pitch will be in the next `baseballr` release.
