### ISSUE TITLE
Missing PO string in savant batter all scraper

### ISSUE THREAD

**Issue by jrhessey** [BillPetti/baseballr#37]
Bill, not sure what happened to this edit before, I thought you added this before, but you're missing the PO and S for the playoffs and spring training in the GT portion of the URL.  It's only the batter_all one, the other 3 have all 3 strings in the url.

**Comment by BillPetti** [comment]
Sorry about that. Got lost when I had to update other parts of their url when they changed something mid-season. Should be working with a reinstall.

**Comment by jrhessey** [comment]
Thanks Bill!
