### ISSUE TITLE
Error in namespaceExport

### ISSUE THREAD

**Issue by MartnAR** [BillPetti/baseballr#4]
I'm trying to install baseballr on R 3.2.3 (both on Windows and Linux) and I'm getting the following error: 
The downloaded source packages are in
	‘/tmp/RtmpRFVgnk/downloaded_packages’
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD INSTALL '/tmp/RtmpRFVgnk/devtools86a798f69fb/BillPetti-baseballr-7a96d6e'  \
  --library='/home/martin/R/x86_64-pc-linux-gnu-library/3.2' --install-tests 

* installing *source* package ‘baseballr’ ...
** R
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error in namespaceExport(ns, exports) : undefined exports: aging_curves
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/martin/R/x86_64-pc-linux-gnu-library/3.2/baseballr’
Error: Command failed (1)

Am I missing something or is the package not yet compatible with version 3.2.3?

**Comment by BillPetti** [comment]
Darn it. Looks like an unfinished function slipped into the NAMESPACE file (aging_curves). I'll need to remove it.  Will reply when it's fixed.

**Comment by BillPetti** [comment]
Okay, give it a try now.

**Comment by MartnAR** [comment]
Yeah, now it's working on both OSs. Thanks for the quick fix.

**Comment by BillPetti** [comment]
You got it. Sorry about that.
