### ISSUE TITLE
30,000 row limit for scrape?

### ISSUE THREAD

**Issue by JakeKlein** [BillPetti/baseballr#42]
There seems to be a limit of 30,000 rows when using the `scrape_statcast` functions.  When I run:

```
start="2015-04-01"
stop="2015-05-01"
statcast_pitching=scrape_statcast_savant_pitcher_all(start,stop)
min(statcast_pitching$game_date)
```
The result is:
> [1] "2015-04-24"

And I get a data set of 30,000 rows

If I change the stop date to an earlier date:

```
start="2015-04-01"
stop="2015-04-10"
statcast_pitching=scrape_statcast_savant_pitcher_all(start,stop)
min(statcast_pitching$game_date)
```

I get:

>[1] "2015-04-05" 

And a data set of ~17,500 rows.

And then if I try a very long window:
```
start="2015-04-01"
stop="2015-07-01"
statcast_pitching=scrape_statcast_savant_pitcher_all(start,stop)
min(statcast_pitching$game_date)
```
I get this nasty error message:

> URL caused a warning. Make sure your date range is correct:
Original warning message:
incomplete final line found by readTableHeader on 'https://baseballsavant.mlb.com/statcast_search/csv?all=true&hfPT=&hfAB=&hfBBT=&hfPR=&hfZ=&stadium=&hfBBL=&hfNewZones=&hfGT=R%7CPO%7CS%7C&hfC=&hfSea=2015%7C&hfSit=&player_type=pitcher&hfOuts=&opponent=&pitcher_throws=&batter_stands=&hfSA=&game_date_gt=2015-04-01&game_date_lt=2015-07-10&team=&position=&hfRO=&home_road=&hfFlag=&metric_1=&hfInn=&min_pitches=0&min_results=0&group_by=name&sort_col=pitches&player_event_sort=h_launch_speed&sort_order=desc&min_abs=0&type=details&'
Error in scrape_statcast_savant_pitcher_all(start, "2015-07-10") : 
  object 'payload' not found

Is this an issue with the package itself or just Savant Search?  And is there an easy work around other than scrapping smaller time frames and putting them together?

**Comment by BillPetti** [comment]
That's an issue with Savant Search. The limit might be 50,000, but I always advise 1 week windows to be safe.
