### ISSUE TITLE
Trying to install and get error  "there is no package called ‘baseballr’ "

### ISSUE THREAD

**Issue by fjcaceres** [BillPetti/baseballr#45]
Hi there Good evening

Iam novice R user but always follow instructions as good as possible
Trying to install baseballr I encounter the following.
PLase help  Thank you

**> require(devtools)**
> install_github("BillPetti/baseballr")
Error in curl::curl_fetch_disk(url, x$path, handle = handle) : 
  Couldn't resolve host name
> library("devtools", lib.loc="C:/Program Files/R/R-3.2.1/library")
**> install_github("BillPetti/baseballr")**
Downloading GitHub repo BillPetti/baseballr@master
from URL https://api.github.com/repos/BillPetti/baseballr/zipball/master
Installing baseballr
Installing 1 package: lubridate

  There is a binary version available (and will be installed) but the
  source version is later:
          binary source
lubridate  1.6.0  1.7.1

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/lubridate_1.6.0.zip'
Content type 'application/zip' length 654624 bytes (639 KB)
downloaded 639 KB

package ‘lubridate’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Javier\AppData\Local\Temp\RtmpCeAFw9\downloaded_packages
Installing 1 package: reldist
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/reldist_1.6-6.zip'
Content type 'application/zip' length 116008 bytes (113 KB)
downloaded 113 KB

package ‘reldist’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Javier\AppData\Local\Temp\RtmpCeAFw9\downloaded_packages
Installing 1 package: rvest
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/rvest_0.3.2.zip'
Content type 'application/zip' length 853411 bytes (833 KB)
downloaded 833 KB

package ‘rvest’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Javier\AppData\Local\Temp\RtmpCeAFw9\downloaded_packages
Installing 1 package: XML

  There is a binary version available (and will be installed) but the
  source version is later:
      binary   source
XML 3.98-1.6 3.98-1.9

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/XML_3.98-1.6.zip'
Content type 'application/zip' length 4298226 bytes (4.1 MB)
downloaded 4.1 MB

package ‘XML’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Javier\AppData\Local\Temp\RtmpCeAFw9\downloaded_packages
Installing 1 package: xml2
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/xml2_1.1.1.zip'
Content type 'application/zip' length 3488697 bytes (3.3 MB)
downloaded 3.3 MB

package ‘xml2’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Javier\AppData\Local\Temp\RtmpCeAFw9\downloaded_packages
"C:/PROGRA~1/R/R-32~1.1/bin/x64/R" --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  "C:/Users/Javier/AppData/Local/Temp/RtmpCeAFw9/devtools430478a12f62/BillPetti-baseballr-c1f2ddf"  \
  --library="C:/Program Files/R/R-3.2.1/library" --install-tests 

* installing *source* package 'baseballr' ...
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
  there is no package called 'tibble'
ERROR: lazy loading failed for package 'baseballr'
* removing 'C:/Program Files/R/R-3.2.1/library/baseballr'
Error: Command failed (1)
**> require(baseballr)**
Loading required package: baseballr
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE, logical.return = TRUE,  :
  there is no package called ‘baseballr’

**Comment by afeierman** [comment]
It looks like the error is caused by R not loading the tibble package, which is a smaller part of the popular [dplyr](http://dplyr.tidyverse.org) package in R. The tibble package provides a faster and more user friendly version of Dataframes. 

This is the code that tipped me off:

`
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) :
there is no package called 'tibble'
ERROR: lazy loading failed for package 'baseballr'
`

Try the following, and write back here if it works or not:

`
install_packages('dplyr')
require('devtools')
install_github("BillPetti/baseballr")
require('baseballr')
`

**Comment by fjcaceres** [comment]
Thank you 
I will try it out this Monday evening and report back here

**Comment by fjcaceres** [comment]
Good evening

Followed your instructions and it was installed ( 20 warnings )
These are the last lines from the installation
*********************************************************

Warning: replacing previous import by 'dplyr::summarise' when loading 'baseballr'
Warning: replacing previous import by 'dplyr::summarize_' when loading 'baseballr'
Warning: replacing previous import by 'dplyr::ungroup' when loading 'baseballr'
Note: the specification for S3 class "difftime" in package 'lubridate' seems equivalent to one from package 'DBI': not turning on duplicate class definitions for this class.
Warning: replacing previous import by 'magrittr::%>%' when loading 'baseballr'
* DONE (baseballr)
> require('baseballr')
Loading required package: baseballr
There were 20 warnings (use warnings() to see them)
**************************************************************

**Comment by afeierman** [comment]
great, glad it worked eventually. there are definitely some issues with package dependencies going on which is worth fixing in the base package. think this issue can be closed
