### ISSUE TITLE
To install baseballr I also was asked to install 'selectr'

### ISSUE THREAD

**Issue by fjcaceres** [BillPetti/baseballr#46]
After installing baseballr thanks to your help, I then went to do your first example and it did not work. t asked for 'selectr'  I installed it and then ran your sample

> standings_on_date_bref("2015-08-01", "NL East", from = FALSE)
**Error in loadNamespace(name) :** there is **no package called ‘selectr’**
> 
> install.packages("selectr", dependencies = FALSE)
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.2/selectr_0.3-1.zip'
Content type 'application/zip' length 159942 bytes (156 KB)
downloaded 156 KB

package ‘selectr’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Javier\AppData\Local\Temp\RtmpoP2z55\downloaded_packages

**> standings_on_date_bref("2015-08-01", "NL East", from = FALSE)**
$`NL East`
   Tm  W  L  W-L%   GB  RS  RA pythW-L%
1 WSN 54 48 0.529   -- 422 391    0.535
2 NYM 54 50 0.519  1.0 368 373    0.494
3 ATL 46 58 0.442  9.0 379 449    0.423
4 MIA 42 62 0.404 13.0 370 408    0.455
5 PHI 41 64 0.390 14.5 386 511    0.374

**Comment by BillPetti** [comment]
`selectr` is a dependency of `rvest`, which is why it was asking you to install it.
