### ISSUE TITLE
Function viz_gb_on_period not found

### ISSUE THREAD

**Issue by darh78** [BillPetti/baseballr#47]
Hey Bill,

I'm glad to know my PRs were merged into the master branch.
I've reinstalled the package and I'm able to run the `standings_on_date_bref` without problems and get the new names on the table.
Nevertheless, the function `viz_gb_on_period` is not available in the package. I do not know if that is related to the difference in case-sensitive names in the function.
![image](https://user-images.githubusercontent.com/7276111/33911068-f44cb9b8-df88-11e7-9a53-8a7bdeaecdc0.png)

Regards.

Daniel.

**Comment by BillPetti** [comment]
Yes, it’s a case issue

**Comment by BillPetti** [comment]
I changed this in the R file. It was trying to export `viz_gb_on_period`, but the function was `viz_GB_on_period`. Try a reinstall and let me know if it works.

**Comment by darh78** [comment]
Hello @BillPetti,

Thanks for the feedback. I tried now and that problem is solved. Nevertheless, there is still an issue when trying to run it. It seems that it's not allowing `separate` function from "dplyr" to run.
![image](https://user-images.githubusercontent.com/7276111/34385024-bb9f22aa-eb17-11e7-9764-7cc9645a2dca.png)

**Comment by BillPetti** [comment]
I looked this over, a few things:

- it looks like `separate` is from `tidyr`, not `dplyr`
- you aren't importing the function, which you should (i.e. `@importFrom tidyr separate`

Can you fix this and then resubmit as a pull request?

**Comment by BillPetti** [comment]
@darh78 is this something you were going to fix and resubmit a pull request for?

**Comment by darh78** [comment]
@BillPetti sure!
I just hadn’t the time. I’ll try it this month.
Regards
