### ISSUE TITLE
running fg_bar_leaders results in incorrect number of dimensions

### ISSUE THREAD

**Issue by kevingarnett** [BillPetti/baseballr#48]
When I run this fg_bat_leaders code on the project website:

`head(fg_bat_leaders(x = 2015, y = 2016, league = "all", qual = 1200, ind = 0)) %>% select(Seasons:AVG)`

I get the following error:

`Error in leaders[1, ] : incorrect number of dimensions`

Is this a me problem?

**Comment by BillPetti** [comment]
They possibly changed the page structure, so the table number is off. Will have a look.

**Comment by kevingarnett** [comment]
I was thinking it might have had something to do with the structure of the source page as well.

**Comment by BillPetti** [comment]
Should work now with a reinstall. Let me know before I close this issue.

**Comment by kevingarnett** [comment]
It seems to be working now. I get the expected output. Thanks again!
