### ISSUE TITLE
Minor league daily player data

### ISSUE THREAD

**Issue by matawith1t** [BillPetti/baseballr#49]
Would it be possible to create a new function that pulls minor league daily data for both hitters and pitchers from Fangraphs? Possibly with the ability to select from all leagues, or specify a particular level?

Thanks for creating this package, it's been a great help!

**Comment by matawith1t** [comment]
I was able to edit your batter_game_logs_fg function to create a new one for MiLB stats. If you'd like, I'd be happy to send it over. Don't have a ton of github experience, so not sure of the best way to do that. Working on the pitcher version as well.

**Comment by BillPetti** [comment]
Cool! If you want to share them here or email them over I can take a look.

**Comment by matawith1t** [comment]
The comments don't support .R files, so sending them over in .txt

I was also interested in the advanced tab metrics, so I pulled both and combined them. Also, the Team column has the level in it (AA, AAA, etc.), so I separated that out into its own variable.

[milb_batter_game_logs_fg.txt](https://github.com/BillPetti/baseballr/files/1589996/milb_batter_game_logs_fg.txt)
[milb_pitcher_game_logs_fg.txt](https://github.com/BillPetti/baseballr/files/1589997/milb_pitcher_game_logs_fg.txt)

**Comment by BillPetti** [comment]
This will be included in the 0.4 release 2018-03-18
