### ISSUE TITLE
pitcher data doesn't query over multiple years

### ISSUE THREAD

**Issue by zrothberg** [BillPetti/baseballr#50]
scrape_statcast_savant_pitcher("2015-03-02","2017-11-25", "592789") 
only scrapes for the year 2015 

https://baseballsavant.mlb.com/statcast_search?hfPT=&hfAB=&hfBBT=&hfPR=&hfZ=&stadium=&hfBBL=&hfNewZones=&hfGT=R%7C&hfC=&hfSea=2017%7C2016%7C2015%7C&hfSit=&player_type=pitcher&hfOuts=&opponent=&pitcher_throws=&batter_stands=&hfSA=&game_date_gt=&game_date_lt=&player_lookup%5B%5D=592789&team=&position=&hfRO=&home_road=&hfFlag=&metric_1=&hfInn=&min_pitches=0&min_results=0&group_by=name&sort_col=pitches&player_event_sort=h_launch_speed&sort_order=desc&min_abs=0#results

is the url that would pull 2015-2017 data
This seems to be the only difference i notice. hfSea=2017%7C2016%7C2015%7C

**Comment by BillPetti** [comment]
To make things cleaner and less likely to break the function forces the query to only cover dates within a single year. For now, I'd rather keep it to a single year.

**Comment by zrothberg** [comment]
It does create some weird issues though if you don't know which pitchers pitched which years. It's obviously not a thing anyone has to deal with regularly. Is anyone really that close to 30k in the actual statcast data?

**Comment by zrothberg** [comment]
It also prevents querying for things like all star break to all star break.

**Comment by BillPetti** [comment]
It's not the 30k limit I am worried about. If you want to take a crack at updating the function to handle the multiple years and submit a pull request I'd be happy to take a look.
