### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by brzaz228** [BillPetti/baseballr#52]
I keep getting this error message when trying to download therefore I cannot use the packagee
* removing 'C:/Users/brett.zaziski/Documents/R/win-library/3.4/baseballr'
Installation failed: Command failed (1)

**Comment by BillPetti** [comment]
Can you post your installation code?

**Comment by brzaz228** [comment]
> require(devtools)
> install_github("BillPetti/baseballr")
Downloading GitHub repo BillPetti/baseballr@master
from URL https://api.github.com/repos/BillPetti/baseballr/zipball/master
Installing baseballr
"C:/PROGRA~1/R/R-34~1.0/bin/x64/R"  \
  --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \

"C:/Users/brett.zaziski/AppData/Local/Temp/RtmpiIp0TQ/devtools5b704d1c798b/BillPetti-baseballr-210a8b0"
\
  --library="C:/Users/brett.zaziski/Documents/R/win-library/3.4"  \
  --install-tests

* installing *source* package 'baseballr' ...
** R
** data
*** moving datasets to lazyload DB
** preparing package for lazy loading
Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck
= vI[[j]]) :
  there is no package called 'acepack'
ERROR: lazy loading failed for package 'baseballr'
* removing 'C:/Users/brett.zaziski/Documents/R/win-library/3.4/baseballr'
Installation failed: Command failed (1)
> require(baseballr)
Loading required package: baseballr
Warning message:
In library(package, lib.loc = lib.loc, character.only = TRUE,
logical.return = TRUE,  :
  there is no package called ‘baseballr’

**Comment by BillPetti** [comment]
This might be the issue:

`Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck
= vI[[j]]) : 
there is no package called 'acepack'`

You don't seem to have the `acepack` package installed.

**Comment by brzaz228** [comment]
Okay thanks I will give it a try.

**Comment by brzaz228** [comment]
It worked thanks Bill.  I am doing an Independent Study regarding Launch
Angle so this is very helpful.  I am not a very experienced programmer.  If
I wanted to pull all the launch angle data from every player for everyone
of their hits that is available do you have any advice on how to do that? I
know that may be an easier SQL command than R but it would be helpful if
you knew how to do it in R.

**Comment by BillPetti** [comment]
You need to loop over all batters and scrape the data. You could build your own database, as I outline here: https://billpetti.github.io/2018-02-19-build-statcast-database-rstats/
