### ISSUE TITLE
SwStr%

### ISSUE THREAD

**Issue by jestarr** [BillPetti/baseballr#53]
Looking at your stat line for stat cast.  Terrific script.  Shouldn't SwStr% include swinging_strikes_blocked and foul_tips?  I did a quick data check on baseball savant and it appears that Whiffs include both of those in addition to swinging_strikes.

**Comment by BillPetti** [comment]
You are correct! Just pushed a fix.

**Comment by jestarr** [comment]
Bill- Looks like this was changed.  Any reason why?

**Comment by BillPetti** [comment]
Changed in what way?

**Comment by jestarr** [comment]
It doesn't look like it includes foul tips, and swinging strikes blocked anymore.
