### ISSUE TITLE
Bug report on missing games for Judge

### ISSUE THREAD

**Issue by zt8zf** [BillPetti/baseballr#55]
I was looking for games for Aaron Judge in July and August of 2017 and found the data are missing. Here is the code I am running.

judge.data.miss <- scrape_statcast_savant_batter(start_date = "2017-07-15", end_date = "2017-8-15", batterid = 621043)
unique(judge.data.miss$game_date)

You can see that only two games for Aaron Judge come up during this stretch. But there should be more, as he only missed three games combined in these months.

**Comment by BillPetti** [comment]
This isn’t a query for Aaron Judge, it’s Carlos Correa. Correa was limited over that time period. Change the batterid and it should work.

**Comment by zt8zf** [comment]
Thanks for catching that error on my part.

**Comment by BillPetti** [comment]
No problemo! That was the issue bug I've had to squash with this package :)
