### ISSUE TITLE
team_results_bref produces "Error: Column 20 must be named"

### ISSUE THREAD

**Issue by ajschrier** [BillPetti/baseballr#58]
Attempted to run the example code for team_results_bref and received the following error:
```
nyy <- team_results_bref('NYY', 2017)
Error: Column 20 must be named
```
standings_on_date_bref function appears to have run as expected.

R 3.4.2/RStudio 1.1.423/macOS 10.13

Let me know if there is any additional logging that would be beneficial.

**Comment by BillPetti** [comment]
Bref added a new column (Org Scheduled) that was breaking things. Pushed a fix.
