### ISSUE TITLE
scrape savant issues

### ISSUE THREAD

**Issue by dsteinberg100** [BillPetti/baseballr#60]
Hi,

When I run this code for A.J. Pollock, it downloads his data, but also everyone else's in the date range. Three days ago it would only download the playerid specified data. 

bat <- scrape_statcast_savant(start_date = "2018-03-28", end_date = paste(Sys.Date() - 1), playerid = 572041, player_type = 'batter')

**Comment by bdilday** [comment]
Thanks for the heads up. This looks like some kind of breaking change on the statcast end. It affects the other scraping functions also, example,

(after installing your update)


```
> library(baseballr)
> bat <- scrape_statcast_savant(start_date = "2018-03-28", end_date = paste(Sys.Date() - 1), playerid = 572041, player_type = 'batter')
[1] "These data are from BaseballSevant and are property of MLB Advanced Media, L.P. All rights reserved."
[1] "Grabbing data, this may take a minute..."
URL read and payload acquired successfully.
> nrow(bat)
[1] 123
``` 

^^^ only 123 rows

```
> bat <- scrape_statcast_savant_batter(start_date = "2018-03-28", end_date = paste(Sys.Date() - 1), batterid =  572041)
[1] "These data are from BaseballSevant and are property of MLB Advanced Media, L.P. All rights reserved."
[1] "Grabbing data, this may take a minute..."
URL read and payload aquired successfully.
> nrow(bat)
[1] 26620
```

^^^ 26k rows

**Comment by jestarr** [comment]
Any particular reason the payload formatting function no longer converts release speed to numeric (from factor)?

**Comment by BillPetti** [comment]
@jestarr not sure why that dropped out. Fixed

**Comment by BillPetti** [comment]
@bdilday Yeah, ideally folks would use the general function, but maybe I'll update the rest when I get time
