### ISSUE TITLE
viz_gb_on_period error: could not find function "hcaes"

### ISSUE THREAD

**Issue by ryurko** [BillPetti/baseballr#62]
I tried running the following code and received the following error:

library(baseballr)
viz_gb_on_period("2018-03-29", "2018-04-14", "NL Central")

Error in hcaes(x = Date, y = GB, group = Team) : 
  could not find function "hcaes"

Since that is from the `highcharter` package I accessed its library directly with library(highcharter) and then it worked, so I'm assuming there's a dependency issue or missing highcharter::hcaes.

**Comment by BillPetti** [comment]
Yup, pushed a fix. Should work on reinstall.
