### ISSUE TITLE
edge_scrape error on dates > 2017

### ISSUE THREAD

**Issue by blacktj** [BillPetti/baseballr#63]
Ran the edge scrape script for any date in 2016 no problem, but I get this error when it's 2017 or 2018

Error in function (type, msg, asError = TRUE)  : 
  Could not resolve host: writefunction

**Comment by BillPetti** [comment]
This appears to be an issue related to the `pitchRx` package. Install the dev version and retry. That should fix things.

**Comment by blacktj** [comment]
Thanks Bill.. yes, it's working now, until I tried to load up the Berrios/Carassco matchup the other night.. I spent 20 minutes wondering why all the PitchFX info was NA. Finally realized it was being played in PR and no cameras to analyze the pitches!
