### ISSUE TITLE
scrape_statcast_savant_all only returning most recent 40000 rows

### ISSUE THREAD

**Issue by dsteinberg100** [BillPetti/baseballr#64]
When I use scrape_statcast_savant_batter_all(start_date = "2018-03-28", end_date = "2018-04-17") or pitcher, all I get is 40000 rows of data exactly with a date range of 2018-04-07 to 2018-04-17, so it appears I only get the most recent 40000 data points.

**Comment by BillPetti** [comment]
I don't think this is an error, at least not on the `baseballr` side. Compare to directly querying from [Statcast Search](https://baseballsavant.mlb.com/statcast_search?hfPT=&hfAB=&hfBBT=&hfPR=&hfZ=&stadium=&hfBBL=&hfNewZones=&hfGT=R%7C&hfC=&hfSea=2018%7C&hfSit=&player_type=batter&hfOuts=&opponent=&pitcher_throws=&batter_stands=&hfSA=&game_date_gt=2018-03-28&game_date_lt=2018-04-17&team=&position=&hfRO=&home_road=&hfFlag=&metric_1=&hfInn=&min_pitches=0&min_results=0&group_by=name&sort_col=pitches&player_event_sort=h_launch_speed&sort_order=desc&min_abs=0#results)). That produces 40k data points. Here's the breakdown by date:

game_date |  # of pitches
-- | --
4/17/18 | 4963
4/16/18 | 2650
4/15/18 | 2949
4/14/18 | 3695
4/13/18 | 4144
4/12/18 | 2404
4/11/18 | 4631
4/10/18 | 4514
4/9/18 | 3578
4/8/18 | 4244
4/7/18 | 2228

Are there specific pitches that are missing?

**Comment by afeierman** [comment]
Would it make sense to add a warning message if the query returns 40k results?
