### ISSUE TITLE
standings_on_date_bref() throwing error

### ISSUE THREAD

**Issue by dhmontgomery** [BillPetti/baseballr#7]
Installed on April 14, 2016, and tried to run the first example in the README: standings_on_date_bref.

Copying and pasting the exact code in the example in, I received an error:

`> standings_on_date_bref("2015-08-01", "NL East", from = FALSE)`
`Error in function_list[[i]](value) : could not find function "html_text"`

This same error threw when testing other dates as well.

I'm using R 3.2.0 on a Mac running OS 10.10.5 Yosemite.

**Comment by BillPetti** [comment]
Sorry about that, looks like when we updated the code we didn't have html_text importing from rvest. Should be all set now if you reinstall.
