### ISSUE TITLE
hello. there seems to be a problem in function edge_scrape

### ISSUE THREAD

**Issue by SongGeunil1** [BillPetti/baseballr#78]
when I try to use this function in my computer, error sign that says "Input is not proper UTF-8, indicate encoding !" keep come up, how can i solve this problem?

**Comment by afeierman** [comment]
@SongGeunil1 this sounds like either an issue with your input to the function, or maybe something with your operating system and R. Can you provide a more detailed example, with your computer information, and a code sample of what you're trying to run?

**Comment by BillPetti** [comment]
Yes, this works fine for me. I am closing this issue, but if you still have an issue and can provide more details feel free to reopen or open a new issue.
