### ISSUE TITLE
viz_gb_on_period error: mutate_impl

### ISSUE THREAD

**Issue by timboudreau25** [BillPetti/baseballr#79]
Hi there!

First off, I'm a bit of an R novice. I don't know how devtools or the inner workings of R functions work. that being said, I ran into an error using the viz_gb_on_period function.

code:
viz_gb_on_period("2018-03-29", "2018-04-05", "NL West")

error:
Error in mutate_impl(.data, dots) : 
  Column `x` is of unsupported type quoted call

Currently using R 3.5.1, latest baseballr version. Can provide more details (if provided the function to run to get them).

**Comment by timboudreau25** [comment]
Also, as a side note, could you provide the example query/function used in the Altuve spray chart example from your website?


ggspraychart(data, point_alpha = .6, fill_legend_title = "Hit Type", fill_value = "hit_type",
             fill_palette = c("1"="#A2C8EC", "2"="#006BA4", "3"="#FF940E",
                              "Out"="#595959", "4"="#C85200")) +
  facet_wrap(~game_year, nrow = 2) +
  ggtitle("\nJose Altuve") +
  labs(subtitle = "Spray Charts Since 2013\n")

**Comment by darh78** [comment]
Hi @timboudreau25,

I had the same issue (`Error in mutate_impl(.data, dots)`) some days ago, and I solved by reinstalling the `tidyverse` package, even though it seems that for other people it was solved differently (https://github.com/jbkunst/highcharter/issues/420)

**Comment by saiemgilani** [comment]
This function has been archived, so I am closing this issue.
