### ISSUE TITLE
Get "Error in .[[33]] : subscript out of bounds" with fg_bat_leaders

### ISSUE THREAD

**Issue by rpollack** [BillPetti/baseballr#8]
I get this error no matter what I do:

```
> fg <- fg_bat_leaders(2016, 2016, 0)
Error in .[[33]] : subscript out of bounds
> fg <- fg_bat_leaders(2015, 2016, 0)
Error in .[[33]] : subscript out of bounds
> fg <- fg_bat_leaders(2015, 2016, 4)
Error in .[[33]] : subscript out of bounds
```

Not sure what other info you'd find helpful. Let me know and I will provide it :-)

**Comment by BillPetti** [comment]
Hmmm, looks like the page structure changed at some point. I've made the correction--reinstall and give it another go.

**Comment by rpollack** [comment]
It looks good! Thanks!
