### ISSUE TITLE
possible Parser issue edge_scrape_split

### ISSUE THREAD

**Issue by hoopghetto** [BillPetti/baseballr#80]
Good Evening all,

when i run the code line:

> library(baseballr)
> library(devtools)
> library(XML)
> 
> {edge_scrape_split('2018-08-22', '2018-08-23', 'pitcher')}

I get this error:

> If file names don't print right away, please be patient.
> grabbing new game IDs
> Error in function (type, msg, asError = TRUE)  : <url> malformed

if i remove devtools and xml from the library I get this

> If file names don't print right away, please be patient.
> grabbing new game IDs
> Error in function (type, msg, asError = TRUE)  : 
>   Could not resolve host: 

Is this an issue with the parser or the webpage that its trying to connect too? Also, is their a fix? thanks!

**Comment by BillPetti** [comment]
This works fine for me. I wonder if you need to update `pitchRx` and use the dev version (1.8.4). There was an issue earlier this year where a change in mlbam url structure was causing some errors.
