### ISSUE TITLE
repeated errors in installation

### ISSUE THREAD

**Issue by herbalson** [BillPetti/baseballr#86]
I ran devtools::install_github("BillPetti/baseballr") and got a message about a missing package, installed the missing package and ran install again, another missing package. Got through around a half dozen  of those and now am stuck on a new error that I can't resolve:

Error : object 'hcaes' is not exported by 'namespace:highcharter'

I tried reinstalling the highcharter package and restarting Rstudio but no luck

**Comment by BillPetti** [comment]
Do you have version 0.7.0 of `highcharter`? I know `hcaes()` is in that version.

**Comment by herbalson** [comment]
Was running 0.4 version of highcharter. Needed to upgrade rlang to update highcharter but had version 3.3.4 of R so needed to upgrade R then rlang then highcharter and...success! Thanks for the help!
