### ISSUE TITLE
Subscript out of bounds with ncaa_scrape

### ISSUE THREAD

**Issue by tshurtz** [BillPetti/baseballr#87]
Get this error: 

`ncaa_dat <- ncaa_scrape(28, 2018, "batting")`
`Error in .[[3]] : subscript out of bounds`

**Comment by BillPetti** [comment]
This works fine for me. Any other information that would help me reproduce the error?

**Comment by tshurtz** [comment]
Hello Bill, 

I ran it again just now and worked fine. Not sure why it didn't work before, thanks for looking into it!
