### ISSUE TITLE
velo_monthly function

### ISSUE THREAD

**Issue by taehoonhan** [BillPetti/baseballr#9]
Hello all,

I've written a function that generates a plot of monthly averages of release velocity of given a dataset and updated it so that it is applicable for the Statcast data in the baseballr package. I'd like to contribute developing the package by writing functions that visualize Statcast and PITCHf/x data. 

This following code would generate a plot that shows how Justin Verlander's velocity changed over seasons.

library(ggvis)
library(xts)
library(baseballr)

#Using ggvis and xts packages, function will generate a plot of monthly average of release velocity of given a dataframe.  

#Justin Verlander's 2013-2016 statcast data
verlander <- scrape_statcast_savant_pitcher(start_date = "2013-04-06", end_date = "2016-10-31",pitcherid =434378) 

velo_monthly <- function(df,overplot=F ,fastball="both"){
  
  
  #Fastball vs. Non-fastball
  
  df$fastball <- as.factor(df$pitch_type %in% c("FA","FF","FC","FT","FS"))
  levels(df$fastball) <- c("F", "NF")
  
  if(fastball=="NF"){
    ndf <- df %>%filter(fastball=="NF")
    shapes <- "cross"
  }  else if(fastball=="F"){
    ndf <- df %>% filter(fastball=="F")
    shapes <- "circle"
  }else {
    ndf <- df
    shapes <-"diamond"
  }
  
  #Time Series
  
  idx <- ndf$game_date
  df_ <- xts(ndf[,c("pitcher","game_date","inning","fastball","pitch_type","start_speed")],order.by=idx)
  
  #Monthly avg of velocity
  
  mthlySumm <- apply.monthly(df_[,6],mean,na.rm=T)
  mthlysum <- as.data.frame(coredata(mthlySumm))
  
  
  mthdat <- as.data.frame(mthlysum[,1])
  names(mthdat) <- "velo_mon"
  mthdat$period <- index(mthlySumm)
  mthdat$seasonYear <- year(mthdat$period)
  mthdat$month <- month(mthdat$period)
  
  
  #overplot over seasonYear
  
  if(overplot==F){
    ans <-mthdat %>% ggvis(~period,~velo_mon) %>%layer_points(fill=~as.factor(seasonYear),shape:=shapes) %>% group_by(seasonYear) %>% layer_smooths(stroke=~as.factor(seasonYear)) %>%add_axis("x",title=paste(df$player_name[1],min(df$game_date),max(df$game_date)),subdivide = 2) %>% add_axis("y", title="Velocity Monthly Average",subdivide=4) %>%add_legend(c("fill","stroke"), title = "Season", orient = "right")
    
    
  }else{
    ans<-mthdat %>% ggvis(~month,~velo_mon) %>%layer_points(fill=~as.factor(seasonYear),shape:=shapes) %>% group_by(seasonYear) %>% layer_smooths(stroke=~as.factor(seasonYear))%>%add_axis("x",title=paste(df$player_name[1],min(df$game_date),max(df$game_date)),subdivide = 2) %>% add_axis("y", title="Velocity Monthly Average",subdivide=4) %>%add_legend(c("fill","stroke"), title = "Season", orient = "right")
    
  }
  
  return(ans)
}

#Justin Verlander's 2013-2016 statcast data
verlander <- scrape_statcast_savant_pitcher(start_date = "2013-04-06", end_date = "2016-10-31",pitcherid =434378) 

velo_monthly(verlander)

velo_monthly(verlander,fastball="NF")
velo_monthly(verlander,overplot=TRUE,fastball="F)

**Comment by jrhessey** [comment]
I've tried using this function and it doesn't look like it's the complete script.  When I run it, I end up with the + after the last velo_monthly line instead of the > sign and nothing actually plots.
