### ISSUE TITLE
get_mlb_probables() bugging when one of the SPs not announced

### ISSUE THREAD

**Issue by colincharles** [BillPetti/baseballr#92]
I added some if statements inside the function to create empty entries for when a starting pitcher for a game has not been announced.

    get_probables_mlb = function(game_pk){
      oldw <- getOption("warn")
      options(warn = -1)
      api_call <- paste0("http://statsapi.mlb.com/api/v1.1/game/", 
                         game_pk, "/feed/live")
      payload <- jsonlite::fromJSON(api_call)
      probable <- payload$gameData$probablePitchers %>% purrr::map_df(~as.data.frame(.))
      
      if(nrow(probable) == 1){
        if(is.null(payload$gameData$probablePitche$'away')){
          df.temp <- data.frame(id = NA, fullName = "TBA", link = "")
          probable <- dplyr::bind_rows(df.temp, probable)
        } else{
          df.temp = data.frame(id = NA, fullName = "TBA", link = "")
          probable <- dplyr::bind_rows(probable, df.temp)
        }
        
      } else if(nrow(probable) == 0){
        df.temp <- data.frame(id = NA, fullName = "TBA", link = "")
        probable <- dplyr::bind_rows(df.temp, df.temp)
      }
      parse_teams <- function(payload_teams) {
        return_table <- tibble(team = payload_teams$name, team_id = payload_teams$id)
        return(return_table)
      }
      away_team <- parse_teams(payload$gameData$teams$away)
      home_team <- parse_teams(payload$gameData$teams$home)
      teams <- dplyr::bind_rows(away_team, home_team)
      table <- dplyr::bind_cols(probable, teams)
      table <- table %>% dplyr::mutate(game_pk = payload$gamePk, 
                                       game_date = stringr::str_sub(payload$gameData$game$calendarEventID, 
                                                                    -10, -1)) %>% dplyr::select(game_pk, game_date, fullName, 
                                                                                                id, team, team_id)
      options(warn = oldw)
      return(table)
    }    

    get_probables_mlb(566781)

**Comment by BillPetti** [comment]
Found the original code--something happened with the commit and it never made it in. This is now fixed via [166fb30780698df6226979c4d32bdcc95b1e73cd](https://github.com/BillPetti/baseballr/commit/166fb30780698df6226979c4d32bdcc95b1e73cd): 

```
> get_probables_mlb(566487)
# A tibble: 2 x 6
  game_pk game_date  fullName id    team                 team_id
    <int> <chr>      <lgl>    <lgl> <chr>                  <int>
1  566487 2019-05-10 NA       NA    Cincinnati Reds          113
2  566487 2019-05-10 NA       NA    San Francisco Giants     137
```
