### ISSUE TITLE
Error in daily_batter_bref() with early date

### ISSUE THREAD

**Issue by zfeld3** [BillPetti/baseballr#93]
Trying to do analysis on DiMaggio's hit streak/other hitters over that time using daily_batter_bref() and got his error

data <- daily_batter_bref("1941-05-15", "1941-07-17")
Error in names(df) <- `*vtmp*` : 
  'names' attribute [4] must be the same length as the vector [0]

Is there a limit to how far back this function goes?

**Comment by BillPetti** [comment]
I believe so, yes, but there appear to be issues now with pulling any data outside of the current year. I'll need to investigate this a little more to see if prior years can still be accessed.

**Comment by BillPetti** [comment]
It appears to only go back to 2008
