### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by SaborTheWaverunner** [BillPetti/baseballr#94]
Whenever I try to install the package, i get the following error: "Error: (converted from warning) unable to access index for repository http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5:
  cannot open URL 'http://www.stats.ox.ac.uk/pub/RWin/bin/windows/contrib/3.5/PACKAGES'"

I'm a relative neophyte to R, but I'd appreciate any ehlp!

**Comment by BillPetti** [comment]
It is not available on CRAN. You have to install from GitHub. See the README file.
