### ISSUE TITLE
Error in select(., season, Name...)could not find function "select"

### ISSUE THREAD

**Issue by cruxoner** [BillPetti/baseballr#96]
I'm just going through your tutorial. The "standings_on_date_bref" command works, but I get the following error with the "daily_pitcher_bref" code:

Error in select(., season, Name, IP, ERA, SO, uBB, HBP, HR, FIP, wOBA_against,  : 
  could not find function "select"

**Comment by BillPetti** [comment]
Looks like you don’t have `dplyr` loaded in your environment. I missed having that function imported for that function, but can fix that in a later release.

**Comment by BillPetti** [comment]
Fixed by [e56f0c6a8db1ed69ce187b4b48bf5ba2e0d908bc](e56f0c6a8db1ed69ce187b4b48bf5ba2e0d908bc)
