### ISSUE TITLE
Make latest version available on CRAN (?)

### ISSUE THREAD

**Issue by afeierman** [BillPetti/baseballr#97]
Hey @BillPetti, 

I've noticed a lot of the issues raised here are related to install / the package not being updated on CRAN. Is there a technical reason why it hasn't been updated, or just lack of time? If so, I could put together a PR to align the code base with CRAN policies

**Comment by BillPetti** [comment]
It's a fair question. I never intended to release this on CRAN. But as it's evolved, maybe it is time. There would still be flexibility to release new features flexibly through GitHub, etc. In terms of getting it ready for CRAN, definitely a lack of time on my part. If you want to take the current release in the `master` branch and try to get it ready that would be great. Any substantive changes can live in the `development_branch` in the meantime.

**Comment by beanumber** [comment]
I could maybe help with this.

**Comment by saiemgilani** [comment]
Closed by #255
